/* Original classroom scenarios for AP Unit 1 topics 1.4 and 1.5. */
(() => {
  'use strict';
  const U=window.IRONCREST_UNIT1,L=window.IRONCREST_LEARNING,S=window.IRONCREST_STORY;
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const definitions=[
    {id:'U1-004',name:'Borrowed Voice',topic:'1.4 · AI-Based Cybersecurity Attacks',theme:'AI-assisted deception & information exposure',description:'A familiar-sounding voice asks for a confidential export. Verify the request, inspect the AI-tool trail, and separate suspicion from proof.',packet:'borrowed-voice-v1',icon:'04'},
    {id:'U1-005',name:'Signal or Noise',topic:'1.5 · Leveraging AI in Cyber Defense',theme:'AI-assisted defense & human review',description:'An AI triage tool flags a backup and overlooks a risky session. Review its evidence and recommendations before deciding what to contain.',packet:'signal-or-noise-v1',icon:'05'}
  ];
  U.catalog.push(...definitions);
  const record=(prefix,i,row)=>({id:prefix+'-'+String(i+1).padStart(3,'0'),time:row[0],user:row[1],ip:row[2],event:row[3],result:row[4],resource:row[5],details:row[6]});
  const evidence=(prefix,rows)=>rows.map((r,i)=>({id:prefix+'-E'+(i+1),title:r[0],desc:r[1],content:'<h2>'+esc(r[0])+'</h2><p>'+esc(r[2])+'</p>'}));
  const rows4=[
    ['10:00:00','rpatel','10.24.1.18','LOGIN_SUCCESS','SUCCESS','Orchard-LT-18','Managed device; normal office network; approved MFA.'],
    ['10:02:10','rpatel','—','CALL_RECEIVED','RECORDED','Reception voicemail','Caller claims to be director Elena West. Reception says the voice sounds familiar; caller number is unverified.'],
    ['10:03:00','mail-gateway','203.0.113.41','MESSAGE_DELIVERED','DELIVERED','orchard-review.example','Polished English requests a customer-list export before a 10:15 deadline. Display name: Elena West.'],
    ['10:04:20','rpatel','10.24.1.18','FILE_READ','SUCCESS','customer-renewals.csv','Read on managed workstation. Reading a file does not show where its contents subsequently went.'],
    ['10:05:10','rpatel','10.24.1.18','AI_PROMPT_SUBMIT','ACCEPTED','Personal assistant account','Proxy records an outgoing prompt, 640 bytes. Payload is not available in this log.'],
    ['10:05:12','assistant','—','AI_RESPONSE','RECEIVED','Personal assistant account','Summary claims that customer lists may be shared for urgent director reviews. Response cites a public blog.'],
    ['10:06:00','rpatel','10.24.1.18','UPLOAD_ATTEMPT','BLOCKED','orchard-review.example','DLP blocked customer-renewals.csv; file label: Confidential. This record establishes that this upload was blocked.'],
    ['10:07:00','slee','10.24.1.23','FILE_UPLOAD','SUCCESS','Approved CRM','Scheduled account update by a different employee; approved destination.'],
    ['10:08:30','rpatel','10.24.1.18','USER_REPORT','RECEIVED','Help desk T-414','Employee reports unexpected voice request and AI policy advice.'],
    ['10:10:00','help-desk','—','CALLBACK_STARTED','CONNECTED','Internal directory number','Help desk uses the director’s number from the managed staff directory, not the message. Interview content is in Evidence Locker.'],
    ['10:11:00','web-audit','—','SOURCE_CHECK','MISMATCH','AI-cited blog','Public blog recommends emergency sharing; internal policy owner and revision are absent. Publication alone does not establish training-set inclusion.'],
    ['10:12:00','rpatel','10.24.1.18','SESSION_REVIEW','NO NEW SESSION','Identity provider','No unfamiliar successful login in the reviewed 10:00–10:12 window. This is not a claim about all systems or times.']
  ];
  const rows5=[
    ['02:00:00','svc-backup','10.30.2.9','BACKUP_START','SUCCESS','Approved backup vault','Job B-217 begins; service-account baseline permits this scheduled job.'],
    ['02:01:00','svc-backup','10.30.2.9','DATA_TRANSFER','SUCCESS','Approved backup vault','4.2 GB transferred; destination is in the approved vault inventory.'],
    ['02:01:02','triage-model','—','AI_CLASSIFICATION','HIGH RISK','Job B-217','Score 0.94 for unusually high volume. Score is a model output, not a verified probability or verdict.'],
    ['02:03:00','nrivera','198.51.100.63','LOGIN_FAILURE','FAILURE','Cloud identity','Unknown browser, session candidate S-88.'],
    ['02:03:10','nrivera','198.51.100.63','LOGIN_FAILURE','FAILURE','Cloud identity','Same account and source; repeated attempt.'],
    ['02:03:30','nrivera','198.51.100.63','LOGIN_SUCCESS','SUCCESS','Session S-88','Unknown browser; authentication succeeded. Human actor is not identified.'],
    ['02:03:31','triage-model','—','AI_CLASSIFICATION','LOW RISK','Session S-88','Score 0.08. Model used source reputation and login result; later mailbox events were not input features.'],
    ['02:04:10','nrivera','198.51.100.63','FORWARD_RULE_CREATE','SUCCESS','Session S-88','Rule forwards new mail externally to archive@review-mail.example. Authorization has not yet been verified.'],
    ['02:05:00','ai-assistant','—','CONFIG_DRAFT','NOT APPLIED','Draft D-51','Suggests disabling identity audit logs to reduce alert volume. No human approval.'],
    ['02:05:20','ai-assistant','—','RULE_DRAFT','NOT APPLIED','Draft R-52','Suggests alerting on every transfer larger than 1 GB, regardless of destination or approved job.'],
    ['02:06:00','ai-assistant','—','CODE_REVIEW','NOT APPLIED','Parser patch P-53','Suggests dropping unrecognized event types. A developer has not reviewed or tested the patch.'],
    ['02:07:00','automation','—','RESPONSE_ACTION','HELD FOR REVIEW','S-88 / B-217','No session revocation or host isolation has run. High-impact actions require authorized review.'],
    ['02:08:00','svc-backup','10.30.2.9','BACKUP_COMPLETE','SUCCESS','Job B-217','Approved vault records successful completion; checksum confirmation is in Evidence Locker.'],
    ['02:10:00','analyst','10.30.1.4','TRIAGE_OPEN','IN PROGRESS','Incident T-515','Analyst reviews original logs alongside model outputs; no final incident determination yet.']
  ];
  definitions.forEach((d,i)=>{
    const attack=i===0;
    window.IRONCREST_CASES[d.id]={id:d.id,title:d.name,queueStatus:'OPEN',priority:'HIGH',topic:d.topic,credits:3,roles:[...window.IRONCREST_CONFIG.teams],mission:attack?'Verify an urgent request and assess possible information exposure.':'Evaluate AI triage and review proposed defenses before approving action.',brief:attack?'Orchard Analytics employee rpatel received an unexpected director request, consulted a personal AI assistant, and attempted an upload. Establish what left the workstation and whether the request was authorized.':'Riverton Services uses AI to help triage security events. A backup received a high-risk label while an unfamiliar session received a low-risk label. Assess both against the underlying records.',standard:'Cite observations. Separate supported hypotheses from confirmed outcomes. Identify what additional evidence you need.',telemetryName:attack?'Communication and data-handling timeline':'AI triage and identity timeline',telemetryKicker:'DEFENDER SOURCES · ORIGINAL CASE RECORDS',recordLabel:'events',objective:attack?'Decide what was requested, what was exposed, and which safeguards are needed.':'Decide which activity merits response and which AI proposals need correction.',objectiveSteps:['Inspect the timeline and compare it with authorized activity.','Use three evidence credits to test your most important uncertainties.','Document your observations and proposed response.'],columns:[{key:'time',label:'TIME'},{key:'user',label:'SOURCE'},{key:'ip',label:'ADDRESS'},{key:'event',label:'EVENT'},{key:'result',label:'RESULT'},{key:'resource',label:'RESOURCE'}],records:(attack?rows4:rows5).map((row,n)=>record(attack?'AIV':'AID',n,row)),evidence:evidence(attack?'AIV':'AID',attack?[
      ['Director callback','Check authorization using an independent contact.','Help desk reached Elena West through the maintained staff directory. She denies requesting the export or calling rpatel. Her denial supports impersonation; it does not establish voice-generation technology or identify the caller.'],
      ['AI conversation export','Determine what the accepted prompt contained.','Authorized export from rpatel’s personal assistant account contains a customer name, renewal date, and confidential account value copied into the 10:05 prompt. The assistant received those fields. The export contains no evidence that the provider trained a model on them or that another user retrieved them.'],
      ['Data handling policy','Compare the request and AI advice with approved rules.','Orchard policy revision 12, maintained by its data owner: Confidential customer information belongs only in approved business systems. Personal AI accounts and external review sites are not approved. Urgent requests do not waive independent authorization.'],
      ['Gateway transfer review','Check the scope of the blocked upload.','DLP recorded zero file bytes sent for the blocked 10:06 upload. The separate 10:05 assistant prompt was accepted. Blocking one file transfer does not undo information already sent through another channel.'],
      ['Voice review','Investigate the voice claim without relying on familiarity.','The available compressed voicemail has no authenticated provenance. Staff recognize a similar voice, but this cannot distinguish a genuine recording, an imitation, or synthesis. No generation-project file or verified provider record was recovered.'],
      ['Public-source review','Test whether the AI policy citation is authoritative.','The cited blog has no Orchard policy authority and conflicts with revision 12. Its author and relationship to the caller remain unverified. The investigation has no model-training records; the blog’s existence does not prove training-data poisoning.']
    ]:[
      ['Backup change ticket','Check whether the high-volume activity was expected.','Approved ticket B-217 permits the 02:00 backup from 10.30.2.9 to the listed vault. Destination and completion checksum match the ticket. These observations support benign backup activity despite the high-risk label.'],
      ['Account-owner interview','Test the authorization of session S-88.','Contacted through a verified channel, nrivera denies the 02:03 login and external forwarding rule. Combined with the session records, this supports unauthorized activity. It does not show how access was obtained.'],
      ['Model inputs and validation','Find what the model could and could not evaluate.','This triage version uses login outcome, source reputation, and transfer volume. It does not ingest mailbox-rule events. Test results include both false positives and missed attacks; scores are not calibrated probabilities. Review needs source correlation and ongoing validation.'],
      ['Draft configuration review','Assess D-51 and R-52 before implementation.','D-51 would remove identity audit visibility. R-52 would repeatedly flag approved large backups and miss small unauthorized transfers. The security engineer recommends retaining logs, incorporating approved-job context, testing against benign and suspicious examples, and monitoring rule performance. No change has been applied.'],
      ['Parser patch review','Assess the AI-generated code suggestion.','Patch P-53 discards event names it does not recognize, including FORWARD_RULE_CREATE. The developer rejects it pending a revision that preserves unknown records for review and tests both known and new events. AI-generated code requires knowledgeable review before deployment.'],
      ['Response authority and session check','Identify an authorized, verifiable response.','The incident lead may revoke S-88 and disable the unapproved forwarding rule after evidence preservation. Analysts must verify token rejection and absence of the rule, and monitor for recurrence. Automated low-impact alert creation is allowed; broad host isolation requires approval and a rollback plan.']
    ]),assessment:{fields:[],reportLabels:{}}};
  });
  const cards=(observed,supports,limits,need,protection)=>[['OBSERVED · PROVES','What the records establish',observed],['SUPPORTS','What the pattern suggests',supports],['DOES NOT PROVE','Where certainty stops',limits],['NEED','How to strengthen the claim',need],['PROTECTION','Choose a proportionate safeguard',protection]];
  L.data['U1-004']={title:'AI-assisted attacks and information exposure',topic:definitions[0].topic,page:46,objectives:[['1.4.A','Explain AI-assisted adversary capabilities.'],['1.4.B','Explain protections against AI-related risks.']],definition:'AI can make deception convincing and inexpensive. Treat identity claims, generated advice, and sensitive inputs as separate trust decisions.',cards:cards('In the practice scene, a caller requests confidential data and the employee sends a short extract to a personal assistant.','The unverified request merits an impersonation investigation; the prompt is a separate exposure path.','Voice familiarity cannot establish identity or synthesis. Sending a prompt does not prove model training or later disclosure to others.','Verify through an independently obtained contact; inspect the actual prompt and approved data policy.','Use independent verification or a prearranged secret where appropriate, maintain MFA, keep sensitive data out of unapproved tools, and check generated claims against authoritative sources.'),terms:[['Voice cloning','Synthesized speech that imitates a person; familiarity is not authentication.'],['AI-assisted phishing','AI helps tailor or polish a deceptive message.'],['Prompt exposure','Information is sent as input to an AI service.'],['Data extraction','An adversary may try to elicit sensitive information through prompts; successful extraction needs evidence.'],['Training-data poisoning','Manipulated training content can influence later outputs; a false web page alone does not prove inclusion.'],['AI-assisted reconnaissance','Automation helps assemble public information about a target.'],['AI-assisted coding','AI can help discover flaws or adapt malicious code; capability is not evidence of its use here.'],['Independent verification','Check through a trusted route obtained separately from the request.'],['Data minimization','Share only approved information needed for a legitimate purpose.']],cisco:'Foundational reinforcement: Section 2.2 (infiltration methods) and Section 3.4 (online privacy). Apply these concepts to AI-assisted deception and prompt sharing; these are not dedicated AI lessons.',cyber:'Foundational reinforcement: Unit 2 — The Human Factor; Unit 9 — Securing Online Components. Apply verification and information-protection concepts to the AI scenario.',transfer:'Compare a familiar voice, a polished message, and an AI-generated policy answer. For each, name an independent verification source and explain what it would establish.'};
  L.data['U1-005']={title:'AI-assisted defense with human review',topic:definitions[1].topic,page:48,objectives:[['1.5.A','Evaluate AI-assisted security changes with qualified review.'],['1.5.B','Explain AI-supported detection and response.']],definition:'AI can prioritize large event streams and suggest defenses. Analysts still need context, testing, and authority to decide which actions are justified.',cards:cards('The practice queue labels a backup high risk and a session low risk; a later mailbox event is outside the model’s inputs.','The classification mismatch supports reviewing both the data inputs and the decision process.','A high score does not prove an attack. A low score does not establish safety, and a draft recommendation is not an applied change.','Compare source records, approved changes, user authorization, model inputs, and validation results.','Review configurations, code, and detection rules with the relevant expert. Test changes, retain visibility, and use timely responses with clear scope and verification.'),terms:[['Machine-learning classification','A model assigns a category using patterns in its inputs.'],['False positive','Benign activity is flagged as suspicious.'],['False negative','Malicious activity is missed or labeled benign.'],['Feature','An input used by a model; omitted events may escape its analysis.'],['Human review','A knowledgeable person evaluates evidence and proposed changes.'],['Detection rule','Criteria used to flag events for investigation.'],['Automated response','A system takes a predefined action after a trigger.'],['Validation','Test performance against relevant benign and malicious examples.']],cisco:'Foundational reinforcement: Section 4.1 (cybersecurity devices and technologies) and Section 4.2 (behavior-based defense). Use these to evaluate AI-supported monitoring; the mapping does not claim a dedicated AI module.',cyber:'Foundational reinforcement: Unit 8 — Network and System Threats; Unit 9 — Securing Online Components. Connect detection context and controls to review of AI recommendations.',transfer:'Design a validation set with one approved backup, one suspicious session, and one unfamiliar event type. Explain what each reveals about the classifier, detection rule, or parser.'};
  const stage=(view,title,task,look,question,choices,answer,feedback,next)=>({view,title,task,look,action:'Read the screen, then answer the checkpoint below.',question,choices,answer,feedback,next});
  U.lessons['U1-004']=[
    stage('Employee workstation','Know the approved route.','Act as Avery, an Orchard employee preparing a customer review.','The internal directory and data policy are independent verification sources.','Which source should Avery use to verify an unexpected director request?',['The number supplied by the caller.','The maintained internal staff directory.','The familiar sound of the caller’s voice.'],1,'The directory supplies an independent contact route. Verify the request before sharing information.','Observe the deception →'),
    stage('Adversary perspective','A convincing voice is a tactic.','Observe how the director’s identity is imitated in this fictional lesson.','The scenario director reveals AI use here; the later case will require its own evidence.','What makes this tactic risky?',['A convincing imitation may persuade someone to skip verification.','AI-generated messages always contain obvious spelling errors.','A familiar voice guarantees authorization.'],0,'Voice synthesis and polished wording can make deception persuasive. Neither authenticates the requester.','Switch to the employee →'),
    stage('Employee inbox','Pause before the export.','Read the message paired with the voice request.','The message asks for sensitive data and discourages a callback.','What should Avery do next?',['Upload now to meet the deadline.','Ask the same caller whether the request is real.','Verify through the known directory and approved workflow.'],2,'Verify through a separate trusted route. The next screen follows a fictional unsafe choice so you can inspect the consequences.','Inspect the AI consultation →'),
    stage('Employee outcome','Sending a chat message can expose customer data.','Follow Avery’s decision to ask a personal AI chatbot about the director’s request.','The message includes a customer name and a confidential renewal value.','After Avery sends this message, what information has been shared with the AI service?',['The entire customer database.','The customer name and renewal value included in the message.','Nothing, because Avery has not uploaded a file.'],1,'The message itself contains confidential data. Sending it shares those details with the AI service, even without a file upload. It does not establish that the caller received them.','Inspect defender records →'),
    stage('SOC analyst','Investigate two separate paths.','Compare the accepted prompt with the blocked file transfer.','One safeguard stopped one transfer; it did not undo the other.','Which conclusion follows from this defender snapshot?',['The blocked upload means no information left by any route.','A similar voice proves a cloned recording.','The file upload was blocked, while a separate prompt was accepted; inspect its contents.'],2,'Keep the channels separate. The proxy alone does not reveal prompt contents or establish AI voice generation.','Reveal the AP lens →'),
    stage('AP Exam Lens','Verify claims and protect inputs.','Connect the scenario to Topic 1.4.','AI can assist impersonation, phishing, reconnaissance, coding, and misleading information.','Which protection addresses inaccurate AI-generated policy advice?',['Compare it with the authoritative policy maintained by the organization.','Trust it if the answer is confident.','Assume any cited public page is an internal policy.'],0,'A stable, authoritative source checks the claim. Do not feed confidential data into an unapproved tool to perform that check.','Begin defender-only replay →'),
    {view:'Defender-only replay',title:'Accept Borrowed Voice.',task:'Investigate rpatel’s case using its own records.',look:'The training character Avery is not the case employee.',action:'Accept the assignment, inspect sources, and finish the Final FRQ.'}
  ];
  U.lessons['U1-005']=[
    stage('SOC workstation','Start with the approved job.','Act as Jordan, a junior analyst reviewing an overnight queue.','The backup ticket defines an expected source, destination, and time.','What helps evaluate an alert about a large transfer?',['The size alone.','The model’s confidence alone.','Compare source, destination, timing, and authorization with the approved job.'],2,'The baseline supplies context that transfer size alone lacks.','Observe the coverage gap →'),
    stage('Adversary perspective','A model sees only its inputs.','Observe a fictional account-abuse attempt.','The teaching view reveals intent; the triage model cannot see that view.','Why might the model miss suspicious mailbox activity?',['Its inputs omit mailbox-rule events.','A low score prevents an attack from occurring.','A successful login establishes the user’s approval.'],0,'Missing inputs can hide important behavior from a classifier. The defender must correlate other available records.','Review the AI queue →'),
    stage('Analyst queue','Which label deserves trust?','Compare two alerts with their underlying activity.','High and low are triage labels, not final findings.','What should Jordan do?',['Close the low-risk session without reading its records.','Review both against baseline and authorization evidence.','Isolate the backup server because its score is higher.'],1,'Review the original events and context before deciding. A high-volume authorized job and a small unauthorized change require different responses.','Review the draft change →'),
    stage('Proposed change','Do not trade away visibility.','Reveal what the AI’s draft would change.','The proposed setting would disable identity audit logs. It has not been applied.','What is the appropriate next step?',['Apply it because it reduces alerts.','Reject AI help for every task.','Have a qualified reviewer revise and test it while preserving necessary logs.'],2,'A reduction in alerts is not evidence of reduced risk. Review the configuration, detection rule, and code changes before deploying them.','Inspect defender records →'),
    stage('SOC analyst','Respond to behavior, then verify.','Compare an approved backup with an unfamiliar session and new forwarding rule.','The model did not evaluate the later rule creation.','Which next step best addresses the session?',['Preserve records, verify authorization, and use authorized containment if warranted.','Treat a low model score as proof of safety.','Stop every large transfer on the network.'],0,'Target the suspicious behavior, retain evidence, and verify the response. Broad disruption is not justified by a score alone.','Reveal the AP lens →'),
    stage('AP Exam Lens','AI assists; evidence decides.','Connect the scenario to Topic 1.5.','Review recommendations and test detection quality before relying on automation.','What should a detection-rule test include?',['Only attacks already detected by the model.','Both approved activity and suspicious behavior, including missed event types.','Only the number of alerts produced.'],1,'Test false positives and missed attacks. Fast classification is useful when it supports accurate, timely intervention.','Begin defender-only replay →'),
    {view:'Defender-only replay',title:'Accept Signal or Noise.',task:'Investigate Riverton’s overnight AI triage.',look:'Use nrivera, S-88, and B-217 records from this case, not Jordan’s practice scene.',action:'Accept the assignment, inspect sources, and finish the Final FRQ.'}
  ];
  S.stories['U1-004']={intro:'You are Avery at Orchard Analytics. A caller who sounds like your director wants a customer export sent to an unfamiliar review site. You also have an AI assistant open.',goal:'Learn how to verify identity, protect sensitive inputs, and distinguish an observed disclosure from an unproven AI technique. Then investigate a separate case.'};
  S.stories['U1-005']={intro:'You are Jordan in Riverton’s security operations center. An AI tool has ranked overnight events and proposed changes to reduce alert volume.',goal:'Use source evidence and approved activity to evaluate the rankings, review proposed controls, and choose a timely response. Then investigate a separate case.'};
  const windowView=(bar,body)=>'<section class="story-window"><div class="story-bar">'+bar+'</div><div class="story-notices">'+body+'</div></section>';
  const tile=(heading,text)=>'<article><h3>'+heading+'</h3><p>'+text+'</p></article>';
  const originalRender=S.render;
  S.render=(id,index,revealed)=>{
    if(!definitions.some(d=>d.id===id))return originalRender(id,index,revealed);
    const attack=id==='U1-004';
    if(index===0)return windowView(attack?'Orchard Analytics · employee preparation':'Riverton Services · analyst handover',attack?tile('Your task: prepare an internal customer review','Avery may use the approved CRM. Customer account values are Confidential; personal AI accounts and unfamiliar external upload sites are not approved.')+tile('Known verification route','Use the maintained staff directory to reach the director. A voice match or a caller-supplied number is not independent verification.'):tile('Expected overnight activity','Backup job PRACTICE-17 runs at 01:00 from the managed backup host to the approved vault. Its transfer is normally several gigabytes.')+tile('Your task: review AI triage','Compare the tool’s labels with source records and the change ticket. Changes to security configurations, code, or rules need qualified review.'));
    if(index===1)return windowView('Scenario director · teaching view, not case evidence',attack?tile('Impersonation plan','In this fictional practice scene, an adversary uses AI to imitate a public speaker’s voice and polish a message. The goal is to get Avery to send customer data before checking the request.')+tile('Other AI risks to recognize','AI can combine public facts for reconnaissance, assist malicious coding, or produce misleading advice. Sensitive prompts can disclose data; manipulated public content can affect models if incorporated into training. These are capabilities, not findings in your later case.'):tile('Account-abuse objective','In this fictional practice scene, an adversary wants to add an external forwarding rule after signing in. The triage model evaluates login information but does not receive mailbox-rule events.')+tile('What the defender must establish','Intent is revealed only by the teaching camera. The defender needs session records, rule details, and user authorization evidence.'));
    if(index===2)return windowView(attack?'Avery’s inbox · message and voicemail':'Jordan’s queue · AI recommendations',attack?tile('Voicemail transcript · identity unverified','“It’s your director. I need the customer export before the meeting. Use the review link I sent; please don’t call back.”')+tile('Message · from review@orchard-check.example','Subject: Customer review due in ten minutes. Upload customer-renewals.csv to the review site. The language is fluent and the display name matches the director. All addresses here are fictional.'):tile('HIGH RISK · scheduled backup','The tool flags a 4 GB transfer. The destination matches the approved vault and the time matches the change ticket.')+tile('LOW RISK · unfamiliar session','The tool accepts a source-reputation signal. A later mailbox event shows a new external forwarding rule, outside the model’s inputs.'));
    if(index===3&&attack)return '<section class="story-window"><div class="story-bar">Avery’s personal AI chatbot · fictional demonstration</div><div class="story-form"><p><strong>Why Avery opens the chatbot:</strong> Avery wants to know whether the urgent customer-list request is allowed. Instead of checking with the company, Avery copies customer details into a personal chatbot.</p><div class="story-compare"><strong>1 · '+(revealed?'Message Avery sent':'Message Avery is about to send')+'</strong><blockquote>“Someone claiming to be my director wants a customer list. Is it okay to send it? Here is one entry:<br><strong>Customer: Demo Customer<br>Renewal value: $12,000</strong>”</blockquote><p>Company rule: customer names and renewal values are confidential. This personal chatbot is not an approved place to share them.</p></div>'+(revealed?'<div class="story-receipt"><h3>2 · Message received by the AI service</h3><p>The customer name and $12,000 renewal value are now included in a message sent outside the company’s approved systems.</p><p><strong>Key idea:</strong> Pasting information into a chat and pressing Send shares that information—even when no file is uploaded.</p></div><details><summary>What this does not tell us</summary><p>We do not know whether the suspicious caller can see the message or whether the AI provider will use it for model training. Those are separate questions that require evidence.</p></details>':'<p><strong>Your action:</strong> Reveal what happens when Avery sends this message, then answer the question below.</p><button data-story-submit>Show what happens when Avery presses Send →</button>')+'<small>All names and amounts are invented. This demonstration does not send a chat message to an AI service.</small></div></section>';
    if(index===3)return windowView(attack?'Personal AI assistant · simulated input':'Change review · draft only',attack?tile('Avery’s draft prompt','“Is this urgent request allowed? Customer: Demo Customer. Renewal value: $12,000. Can I upload the list?” These fictional fields illustrate confidential business information.')+(revealed?tile('Simulated submission recorded','The service accepted the displayed fields. Its response cites an unaffiliated blog as permission to share. No real data was sent. This receipt does not show provider training or access by the caller.'):'<button data-story-submit>Reveal the fictional submission outcome →</button>'):tile('AI proposal D-PRACTICE','Turn identity audit logging off to reduce alert volume. Also use a size-only transfer rule and discard unknown event types from the parser.')+(revealed?tile('Draft impact revealed · not applied','The configuration removes visibility, the rule ignores approved-job context, and the parser can discard new attack evidence. A security engineer and developer must review and test revisions. No setting was changed.'):'<button data-story-submit>Reveal the proposed change’s impact →</button>'));
    if(index===4)return windowView('SOC · narrower defender snapshot',attack?tile('11:05 · AI prompt accepted','Proxy records an outgoing prompt; this snapshot does not show its payload. Request the conversation export to assess exposure.')+tile('11:06 · customer file blocked','DLP blocks the upload to the unfamiliar site. Inspect each channel separately before concluding what was disclosed.'):tile('01:01 · backup transfer','Source, destination, and time match the approved job. The model’s high-risk label needs contextual review.')+tile('01:04 · forwarding rule','An unfamiliar session creates an external forwarding rule. The model’s low-risk label predates that event. Verify authorization and preserve the session evidence.'));
    return windowView('Teaching scene complete · defender assignment',tile(definitions.find(d=>d.id===id).name,attack?'Investigate rpatel at Orchard Analytics. The case has its own call, assistant prompt, and blocked-upload records. Do not import Avery’s teaching facts.':'Investigate nrivera’s session S-88 and backup B-217 at Riverton Services. Evaluate original records, AI outputs, and unapproved drafts.')+tile('Your finish line','Accept the case, investigate with three evidence credits, then record the Final FRQ and copy it for teacher review. Enrichment links appear after recording.'));
  };
  S.coverage='<section class="unit-how"><h2>Unit 1 topic coverage</h2><p>Activities are available for all five Unit 1 topics. These focused investigations reinforce the curriculum; they do not replace every lesson or essential-knowledge statement.</p><ul><li>1.1 · Social engineering — Chain Reaction</li><li>1.2 · Suspicious website logins — Possible Account Compromise</li><li>1.3 · Public networks — Signal Lost</li><li>1.4 · AI risks — Borrowed Voice</li><li>1.5 · AI defenses — Signal or Noise</li></ul></section>';
  const q=(id,verb,prompt,criterion)=>({id,label:id[0]+'('+id.slice(1)+')',verb,prompt,criterion,...(verb==='Write'?{command:true}:{})});
  const originalPacket=U.packet;
  U.packet=(c,state)=>{
    const item=definitions.find(d=>d.id===c.id);if(!item)return originalPacket(c,state);
    const attack=c.id==='U1-004';
    return {id:item.packet,title:c.title+' · Final FRQ',intro:'Complete Parts A–D after investigating. Cite case records or evidence you unlocked; teaching-scene facts are not case evidence. This original practice uses AP task verbs and a source-based format.',sources:[
      {id:'1',title:c.telemetryName,lines:c.records.map(r=>`${r.id} · ${r.time} · ${r.user} · ${r.ip} · ${r.event} · ${r.result} · ${r.resource} · ${r.details}`)},
      {id:'2',title:'Evidence Locker · your unlocked sources',evidence:c.evidence.map((e,i)=>({...e,ref:'2.'+(i+1)})).filter(e=>state.unlocked.includes(e.id))},
      {id:'3',title:'Proposed policy · assessment stimulus',lines:[attack?'Employees may treat a familiar voice or fluent AI policy answer as approval to share customer data.':'Analysts must accept AI risk labels and deploy proposed configurations, code, and detection rules without further review.','Evaluate the proposed rule in line 1; it is not a description of an approved policy.','Preserve relevant sources and document authorized response actions.']},
      {id:'4',title:'Hypothetical command reference · do not execute',reference:true,lines:['An authorized Linux analyst owns a regular file named ai-review.txt. It has mode 644 and no extended ACLs. This is a separate assessment stimulus, not an incident finding.','Reference: chmod MODE FILE. Three octal digits specify owner, group, and other permissions; read = 4, write = 2, execute = 1. Add values within each digit.','Target: the owner can read and write; group and others have no permissions. This change does not undo prior transfers or revoke cloud sessions.']}
    ],parts:[
      {id:'A',title:'Read the observations',skill:'Detect Attacks',questions:[q('Ai','Identify',attack?'one impersonation or pressure indicator in Source 1. Cite its record ID.':'the high-risk activity and one source-record detail that supports an authorized explanation. Cite a record ID.',attack?'An observed request indicator is identified with its citation; AI generation is not assumed.':'The backup is identified and compared with the approved destination, timing, or job context.'),q('Aii','Describe',attack?'the different outcomes recorded for the assistant prompt and file-upload attempt. Cite both record IDs.':'the sequence of unfamiliar authentication and mailbox activity that the low-risk label does not adequately address. Cite two record IDs.',attack?'The accepted prompt and blocked file transfer are distinguished without assuming an unknown payload.':'Actual session and mailbox actions are described; model labels are not treated as authorization.')]},
      {id:'B',title:'Qualify the conclusion',skill:'Detect Attacks',questions:[q('Bi','Determine',attack?'whether your available sources establish that AI generated the caller’s voice. Support your conclusion and name evidence that could resolve the uncertainty.':'whether the available sources justify treating S-88 as harmless. Support your answer and state any remaining authorization uncertainty.',attack?'The response distinguishes suspected impersonation from proven synthesis and proposes provenance evidence.':'The response weighs suspicious session behavior and any unlocked interview rather than relying on a low label.'),q('Bii','Explain',attack?'why blocking the file upload does not by itself establish that no confidential information left the workstation. Use your available sources and identify any payload uncertainty.':'how the model’s omitted mailbox events can affect detection. Distinguish a possible missed attack from a confirmed false negative if authorization is not yet established.',attack?'The separate accepted prompt is considered; its exact contents are asserted only if supported by unlocked evidence.':'The explanation connects missing inputs to missed behavior and qualifies the conclusion using available authorization evidence.')]},
      {id:'C',title:'Improve the proposed policy',skill:'Mitigate Risk',questions:[q('Ci','Explain',attack?'a replacement for Source 3, line 1 that verifies identity and checks generated advice independently. Explain why it reduces risk.':'a replacement for Source 3, line 1 requiring qualified review of configurations, code, and rules. Explain one concrete harm this could prevent.',attack?'Independent contact and authoritative policy verification replace familiarity or fluency as authorization.':'A relevant expert review and a specific risk such as lost logs, discarded events, or noisy rules are connected.'),q('Cii','Describe',attack?'one control for sensitive AI inputs and one response to possible prior disclosure. State what each cannot guarantee.':'a validation test and a proportionate response for this incident. State how you would verify the response and one limitation.',attack?'Prevention and post-disclosure handling are distinct; neither promises retrieval of all prior copies.':'Testing uses relevant benign/suspicious activity; response, verification, and limitation fit the observations.')]},
      {id:'D',title:'Protect your investigation notes',skill:'Mitigate Risk',questions:[q('Di','Write','one command using Source 4 to apply its target permissions to ai-review.txt. Do not execute it.','chmod 600 ai-review.txt or an exact equivalent grants only owner read/write.'),q('Dii','Explain',attack?'one confidentiality benefit of that change and why it cannot undo a prompt already sent.':'one confidentiality benefit of that change and why it does not contain S-88.','Local file access is restricted; remote exposure or cloud-session containment requires separate action.')]}
    ],extension:{id:'E',title:'Risk-analysis extension',skill:'Analyze Risk · course extension',questions:[q('Ei','Identify','one sensitive asset and a plausible impact. Distinguish potential harm from a confirmed outcome.','A case-relevant asset and impact are identified without asserting unobserved harm.'),q('Eii','Explain','which risk you would prioritize using a case observation, likelihood, potential impact, and one uncertainty.','The priority connects evidence to likelihood and impact and names a meaningful uncertainty.')]}};
  };
})();
