(()=>{const C=window.IRONCREST_CASE;const $=s=>document.querySelector(s);let selected=null;
const state=JSON.parse(localStorage.getItem("ironcrest-u1-001")||'{"credits":3,"unlocked":[],"timeline":[],"notes":""}');
const save=()=>localStorage.setItem("ironcrest-u1-001",JSON.stringify(state));
$("#acceptCase").onclick=()=>{$("#teamName").textContent=$("#roleSelect").value;$("#briefing").classList.add("hidden");$("#console").classList.remove("hidden");render()};
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.view).classList.add("active")});
const types=[...new Set(C.logs.map(x=>x.event))].sort();types.forEach(t=>$("#eventFilter").insertAdjacentHTML("beforeend",'<option>'+t+'</option>'));
function renderLogs(){const q=$("#search").value.toLowerCase(),ef=$("#eventFilter").value,rf=$("#resultFilter").value;const rows=C.logs.filter(x=>(!q||Object.values(x).join(" ").toLowerCase().includes(q))&&(!ef||x.event===ef)&&(!rf||x.result===rf));$("#eventCount").textContent=rows.length+" events";$("#logRows").innerHTML=rows.map(x=>'<tr data-id="'+x.id+'"><td>'+x.time+'</td><td>'+x.user+'</td><td>'+x.ip+'</td><td>'+x.event+'</td><td class="result-'+x.result.toLowerCase()+'">'+x.result+'</td><td>'+x.resource+'</td></tr>').join("");document.querySelectorAll("#logRows tr").forEach(r=>r.onclick=()=>openEvent(r.dataset.id))}
["search","eventFilter","resultFilter"].forEach(id=>$("#"+id).addEventListener(id==="search"?"input":"change",renderLogs));$("#clearFilters").onclick=()=>{$("#search").value="";$("#eventFilter").value="";$("#resultFilter").value="";renderLogs()};
function openEvent(id){selected=C.logs.find(x=>x.id===id);$("#drawerTitle").textContent=selected.id+" // "+selected.event;$("#drawerBody").innerHTML=Object.entries(selected).map(([k,v])=>'<div class="detailrow"><span>'+k.toUpperCase()+'</span><span>'+v+'</span></div>').join("");$("#drawer").classList.remove("hidden")}
$("#closeDrawer").onclick=()=>$("#drawer").classList.add("hidden");$("#pinEvent").onclick=()=>{if(!selected)return;state.timeline.push({time:selected.time,text:selected.id+" — "+selected.user+" — "+selected.event+" — "+selected.details});save();renderTimeline();$("#drawer").classList.add("hidden")};
function renderEvidence(){$("#creditDots").textContent=state.credits?Array(state.credits).fill("●").join(" ")+" "+Array(3-state.credits).fill("○").join(" "):"○ ○ ○";$("#evidenceCards").innerHTML=C.evidence.map(e=>{const u=state.unlocked.includes(e.id);return '<article class="ecard '+(u?"unlocked":"")+'"><small>'+ (u?"UNLOCKED":"AVAILABLE // 1 CREDIT")+'</small><h3>'+e.title+'</h3><p>'+e.desc+'</p><button data-e="'+e.id+'">'+(u?"VIEW EVIDENCE":"REQUEST EVIDENCE")+'</button></article>'}).join("");document.querySelectorAll("[data-e]").forEach(b=>b.onclick=()=>requestEvidence(b.dataset.e))}
function requestEvidence(id){const e=C.evidence.find(x=>x.id===id);if(state.unlocked.includes(id))return showModal(e.content);if(state.credits<=0)return showModal("<h2>No credits remaining</h2><p>Work with the evidence your team has already collected.</p>");showModal('<h2>Evidence Request: '+e.title+'</h2><p>Before spending a credit, tell your SOC Manager:</p><blockquote>What investigative question are you trying to answer, and why would this source help?</blockquote><button id="confirmSpend" class="primary">SPEND 1 CREDIT & REVEAL</button>');setTimeout(()=>$("#confirmSpend").onclick=()=>{state.credits--;state.unlocked.push(id);save();renderEvidence();showModal(e.content)},0)}
function showModal(html){$("#modalBody").innerHTML=html;$("#modal").classList.remove("hidden")}$("#closeModal").onclick=()=>$("#modal").classList.add("hidden");
$("#timelineForm").onsubmit=e=>{e.preventDefault();if(!$("#timelineText").value.trim())return;state.timeline.push({time:$("#timelineTime").value||"—",text:$("#timelineText").value});$("#timelineTime").value=$("#timelineText").value="";save();renderTimeline()};
function renderTimeline(){$("#timelineList").innerHTML=state.timeline.length?state.timeline.map((x,i)=>'<div class="entry"><b>'+x.time+'</b> '+x.text+' <button data-del="'+i+'">×</button></div>').join(""):'<p class="hint">No observations pinned yet.</p>';document.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{state.timeline.splice(+b.dataset.del,1);save();renderTimeline()})}
$("#caseNotes").value=state.notes;$("#caseNotes").oninput=e=>{state.notes=e.target.value;save();$("#saveFlag").textContent="Saved."};
$("#assessmentForm").onsubmit=e=>{e.preventDefault();const a={disposition:$("#disposition").value,account:$("#account").value,strongest:$("#strongest").value,happened:$("#happened").value,proves:$("#proves").value,supports:$("#supports").value,need:$("#need").value};state.assessment=a;save();$("#assessmentForm").classList.add("hidden");$("#submitted").classList.remove("hidden")};
function render(){renderLogs();renderEvidence();renderTimeline()}render()})();