(()=>{const C=window.IRONCREST_CASE,$=s=>document.querySelector(s),KEY="ironcrest-u1-001";let selected=null,pendingEvidence=null,editingAssessment=false;
const defaults={credits:3,unlocked:[],timeline:[],notes:"",evidenceQuestions:{},evidenceAdded:[],team:"Authentication Team",assessment:null};
const state=Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||"{}"));const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
state.timeline=(state.timeline||[]).map(x=>x&&x.type?x:{type:"legacy",time:(x&&x.time)||"—",title:"Migrated V2.1 Finding",source:"Legacy case file",observation:(x&&x.text)||"Imported finding from the earlier console version."});save();
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function showModal(html){$("#modalBody").innerHTML=html;$("#modal").classList.remove("hidden")}function closeModal(){$("#modal").classList.add("hidden")}
$("#roleSelect").value=state.team||"Authentication Team";$("#acceptCase").onclick=()=>{state.team=$("#roleSelect").value;save();$("#teamName").textContent=state.team;$("#briefing").classList.add("hidden");$("#console").classList.remove("hidden");render()};$("#closeDrawer").onclick=()=>$("#drawer").classList.add("hidden");$("#closeModal").onclick=closeModal;$("#resetCase").onclick=()=>showModal('<h2>Reset Case U1-001?</h2><p>This clears this browser\'s timeline, evidence requests, notes, and assessment for this case. Use this before a new student team begins.</p><button type="button" id="confirmReset" class="danger modal-action">RESET CASE</button>');
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.view).classList.add("active");if(b.dataset.view==="assessment")renderAssessment()});
[...new Set(C.logs.map(x=>x.event))].sort().forEach(t=>$("#eventFilter").insertAdjacentHTML("beforeend","<option>"+esc(t)+"</option>"));
function renderLogs(){const q=$("#search").value.toLowerCase(),ef=$("#eventFilter").value,rf=$("#resultFilter").value;const rows=C.logs.filter(x=>(!q||Object.values(x).join(" ").toLowerCase().includes(q))&&(!ef||x.event===ef)&&(!rf||x.result===rf));$("#eventCount").textContent=rows.length+" events";$("#logRows").innerHTML=rows.map(x=>'<tr data-id="'+esc(x.id)+'"><td>'+esc(x.time)+'</td><td>'+esc(x.user)+'</td><td>'+esc(x.ip)+'</td><td>'+esc(x.event)+'</td><td class="result-'+esc(x.result.toLowerCase())+'">'+esc(x.result)+'</td><td>'+esc(x.resource)+'</td></tr>').join("")}
["search","eventFilter","resultFilter"].forEach(id=>$("#"+id).addEventListener(id==="search"?"input":"change",renderLogs));$("#clearFilters").onclick=()=>{$("#search").value="";$("#eventFilter").value="";$("#resultFilter").value="";renderLogs()};$("#logRows").onclick=e=>{const row=e.target.closest("tr[data-id]");if(row)openEvent(row.dataset.id)};
function openEvent(id){selected=C.logs.find(x=>x.id===id);if(!selected)return;$("#drawerTitle").textContent=selected.id+" // "+selected.event;$("#drawerBody").innerHTML=Object.entries(selected).map(([k,v])=>'<div class="detailrow"><span>'+esc(k.toUpperCase())+'</span><span>'+esc(v)+'</span></div>').join("");$("#drawer").classList.remove("hidden")}
$("#pinEvent").onclick=()=>{if(!selected)return;showModal('<h2>Add '+esc(selected.id)+' to Case</h2><p><b>Why does this event matter?</b></p><p class="lead">Explain what you noticed or how it relates to your current hypothesis.</p><textarea id="eventReason" rows="4" placeholder="Analyst observation…" required></textarea><button type="button" id="confirmPin" class="primary modal-action" disabled>ADD TO TIMELINE</button>')};
function renderEvidence(){$("#creditDots").textContent=Array(state.credits).fill("●").join(" ")+" "+Array(3-state.credits).fill("○").join(" ");$("#evidenceCards").innerHTML=C.evidence.map(e=>{const u=state.unlocked.includes(e.id);return '<article class="ecard '+(u?"unlocked":"")+'"><small>'+(u?"UNLOCKED":"AVAILABLE // 1 CREDIT")+'</small><h3>'+esc(e.title)+'</h3><p>'+esc(e.desc)+'</p><button data-e="'+esc(e.id)+'">'+(u?"VIEW EVIDENCE":"REQUEST EVIDENCE")+'</button></article>'}).join("")}
$("#evidenceCards").onclick=e=>{const b=e.target.closest("[data-e]");if(b)requestEvidence(b.dataset.e)};function requestEvidence(id){const ev=C.evidence.find(x=>x.id===id);if(!ev)return;pendingEvidence=ev;if(state.unlocked.includes(id))return showEvidence(ev);if(state.credits<=0)return showModal("<h2>No credits remaining</h2><p>Work with the evidence your team has already collected.</p>");showModal('<h2>Evidence Request: '+esc(ev.title)+'</h2><p>What investigative question are you trying to answer, and why would this source help?</p><textarea id="evidenceQuestion" rows="4" placeholder="Enter your investigative question…" required></textarea><button type="button" id="confirmSpend" class="primary modal-action" disabled>SPEND 1 CREDIT & REVEAL</button>')}
function showEvidence(ev){pendingEvidence=ev;const added=state.evidenceAdded.includes(ev.id);showModal(ev.content+'<div class="evidence-question"><small>YOUR INVESTIGATIVE QUESTION</small><p>'+esc(state.evidenceQuestions[ev.id]||"Previously unlocked evidence")+'</p></div><button id="addEvidence" class="primary modal-action" '+(added?"disabled":"")+'>'+(added?"ADDED TO CASE":"ADD TO CASE")+'</button>')}
$("#timelineForm").onsubmit=e=>{e.preventDefault();const text=$("#timelineText").value.trim();if(!text)return;state.timeline.push({type:"note",time:$("#timelineTime").value||"—",title:"Analyst Observation",source:"Manual entry",observation:text});$("#timelineTime").value=$("#timelineText").value="";save();renderTimeline()};
function sortTimeline(items){return items.map((x,i)=>({...x,_i:i})).sort((a,b)=>{const ta=/^\d\d:\d\d/.test(a.time)?a.time:"99:99:99",tb=/^\d\d:\d\d/.test(b.time)?b.time:"99:99:99";return ta.localeCompare(tb)})}
function renderTimeline(){const items=sortTimeline(state.timeline);$("#timelineList").innerHTML=items.length?items.map(x=>'<div class="entry '+esc(x.type||"legacy")+'"><div class="entrytop"><span class="badge">'+esc(String(x.type||"legacy").toUpperCase())+'</span><b>'+esc(x.time||"—")+'</b><button type="button" data-del="'+x._i+'" title="Remove finding" aria-label="Remove finding">×</button></div><h3>'+esc(x.title||"Finding")+'</h3><div class="entrysource">'+esc(x.source||"")+'</div><p><strong>Analyst observation:</strong> '+esc(x.observation||x.text||"")+'</p></div>').join(""):'<p class="hint">No findings in the case file yet.</p>';renderAssessment()}
$("#timelineList").onclick=e=>{const b=e.target.closest("[data-del]");if(!b)return;e.preventDefault();const i=Number(b.dataset.del);if(!Number.isInteger(i)||i<0||i>=state.timeline.length)return;state.timeline.splice(i,1);save();renderTimeline()};$("#caseNotes").value=state.notes;$("#caseNotes").oninput=e=>{state.notes=e.target.value;save();$("#saveFlag").textContent="Saved.";renderAssessment()};
function populateAssessmentForm(){const a=state.assessment||{};$("#disposition").value=a.disposition||"";$("#account").value=a.account||"";$("#happened").value=a.happened||"";$("#proves").value=a.proves||"";$("#supports").value=a.supports||"";$("#need").value=a.need||"";$("#nextAction").value=a.nextAction||""}
function reportText(){const a=state.assessment||{};const findings=sortTimeline(state.timeline).map(x=>'- '+(x.time||"—")+' | '+(x.title||"Finding")+': '+(x.observation||x.text||"")).join("\n");return `IRONCREST CYBER PARTNERS — SOC BRIEFING\nCase: U1-001 — Possible Account Compromise\nAnalyst Team: ${state.team||"Unassigned"}\n\nDISPOSITION\n${a.disposition||""}\n\nACCOUNT OF CONCERN\n${a.account||""}\n\nINCIDENT ASSESSMENT\n${a.happened||""}\n\nPROVES\n${a.proves||""}\n\nSUPPORTS\n${a.supports||""}\n\nNEED\n${a.need||""}\n\nRECOMMENDED NEXT ACTION\n${a.nextAction||""}\n\nCASE FILE FINDINGS\n${findings||"No findings recorded."}`}
function renderReport(){const a=state.assessment;if(!a)return;$("#reportDisposition").textContent=a.disposition;$("#reportBody").innerHTML='<div class="report-grid"><div><small>ACCOUNT OF CONCERN</small><p>'+esc(a.account)+'</p></div><div><small>ANALYST TEAM</small><p>'+esc(state.team)+'</p></div></div><section><small>INCIDENT ASSESSMENT</small><p>'+esc(a.happened)+'</p></section><div class="triple report-reasoning"><section><small>PROVES</small><p>'+esc(a.proves)+'</p></section><section><small>SUPPORTS</small><p>'+esc(a.supports)+'</p></section><section><small>NEED</small><p>'+esc(a.need)+'</p></section></div><section><small>RECOMMENDED NEXT ACTION</small><p>'+esc(a.nextAction)+'</p></section><section><small>CASE FILE FINDINGS</small>'+sortTimeline(state.timeline).map(x=>'<div class="report-finding"><b>'+esc(x.time)+' · '+esc(x.title)+'</b><span>'+esc(x.observation||x.text||"")+'</span></div>').join("")+'</section>'}
function renderAssessment(){if(!$("#statusTimeline"))return;$("#statusTimeline").textContent=state.timeline.length;$("#statusEvidence").textContent=state.unlocked.length+" / 3";$("#statusNotes").textContent=state.notes.trim()?"SAVED":"NONE";$("#assessmentFindings").innerHTML=state.timeline.length?'<small>CASE FILE FINDINGS</small>'+sortTimeline(state.timeline).map(x=>'<div class="mini-finding"><b>'+esc(x.time)+" · "+esc(x.title)+'</b><span>'+esc(x.observation||x.text||"")+'</span></div>').join(""):'<p class="hint">Your case file has no findings yet. Return to the investigation before making a disposition.</p>';const completed=!!state.assessment&&!editingAssessment;$("#assessmentForm").classList.toggle("hidden",completed);$("#submitted").classList.toggle("hidden",!completed);if(completed)renderReport();else populateAssessmentForm()}
$("#assessmentForm").onsubmit=e=>{e.preventDefault();state.assessment={disposition:$("#disposition").value,account:$("#account").value.trim(),happened:$("#happened").value.trim(),proves:$("#proves").value.trim(),supports:$("#supports").value.trim(),need:$("#need").value.trim(),nextAction:$("#nextAction").value.trim()};editingAssessment=false;save();renderAssessment()};$("#editAssessment").onclick=()=>{editingAssessment=true;renderAssessment();$("#assessmentForm").scrollIntoView({behavior:"smooth",block:"start"})};$("#copyBriefing").onclick=async()=>{const text=reportText(),status=$("#copyStatus");try{await navigator.clipboard.writeText(text);status.textContent="Copied — paste into Schoology."}catch(err){const ta=document.createElement("textarea");ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand("copy");ta.remove();status.textContent="Copied — paste into Schoology."}setTimeout(()=>status.textContent="",3500)};
document.addEventListener("input",e=>{const id=e.target&&e.target.id;if(id==="eventReason"){const b=$("#confirmPin");if(b)b.disabled=!e.target.value.trim()}if(id==="evidenceQuestion"){const b=$("#confirmSpend");if(b)b.disabled=!e.target.value.trim()}if(id==="evidenceReason"){const b=$("#confirmEvidence");if(b)b.disabled=!e.target.value.trim()}},true);
document.addEventListener("click",e=>{const b=e.target&&e.target.closest?e.target.closest("button"):null;if(!b)return;if(b.id==="confirmPin"){e.preventDefault();const t=$("#eventReason");if(!t||!t.value.trim()||!selected)return;state.timeline.push({type:"log",time:selected.time,title:selected.id+" — "+selected.event,source:selected.user+" · "+selected.ip+" · "+selected.resource,observation:t.value.trim()});save();renderTimeline();closeModal();$("#drawer").classList.add("hidden");return}if(b.id==="confirmSpend"){e.preventDefault();const t=$("#evidenceQuestion");if(!t||!t.value.trim()||!pendingEvidence||state.credits<=0)return;if(!state.unlocked.includes(pendingEvidence.id)){state.credits--;state.unlocked.push(pendingEvidence.id)}state.evidenceQuestions[pendingEvidence.id]=t.value.trim();save();renderEvidence();showEvidence(pendingEvidence);return}if(b.id==="addEvidence"){e.preventDefault();if(b.disabled||!pendingEvidence)return;showModal(pendingEvidence.content+'<h3>Why does this evidence matter?</h3><p class="lead">Explain what it proves or supports in your investigation.</p><textarea id="evidenceReason" rows="4" placeholder="Analyst interpretation…"></textarea><button type="button" id="confirmEvidence" class="primary modal-action" disabled>ADD TO CASE FILE</button>');return}if(b.id==="confirmEvidence"){e.preventDefault();const t=$("#evidenceReason");if(!t||!t.value.trim()||!pendingEvidence)return;if(!state.evidenceAdded.includes(pendingEvidence.id)){state.evidenceAdded.push(pendingEvidence.id);state.timeline.push({type:"evidence",time:"EVIDENCE",title:pendingEvidence.title,source:"Evidence Locker",observation:t.value.trim()})}save();renderEvidence();renderTimeline();closeModal();return}if(b.id==="confirmReset"){e.preventDefault();localStorage.removeItem(KEY);location.reload();return}},true);
function render(){$("#teamName").textContent=state.team;renderLogs();renderEvidence();renderTimeline();renderAssessment()}render()})();