window.IRONCREST_CASE={
id:"U1-001",title:"Possible Account Compromise",
logs:[
["08:02:11","mgarcia","10.20.4.18","LOGIN_SUCCESS","SUCCESS","HR-LT-14","Interactive sign-in from managed workstation"],
["08:04:33","rpatel","10.20.4.22","LOGIN_SUCCESS","SUCCESS","FIN-LT-07","Interactive sign-in from managed workstation"],
["08:05:43","jsmith","10.20.4.27","FILE_ACCESS","SUCCESS","Benefits_2026.pdf","Read file from department share"],
["08:08:17","tnguyen","10.20.4.39","LOGIN_SUCCESS","SUCCESS","OPS-LT-03","Interactive sign-in from managed workstation"],
["08:12:26","mgarcia","10.20.4.18","EMAIL_SEND","SUCCESS","mail","Message sent to internal recipient"],
["08:15:52","jsmith","10.20.4.27","EMAIL_READ","SUCCESS","mail","Mailbox activity from managed workstation"],
["08:19:04","rpatel","10.20.4.22","FILE_ACCESS","SUCCESS","Q3_Budget.xlsx","Read file from finance share"],
["08:23:31","akim","10.20.4.51","LOGIN_FAILURE","FAILURE","ENG-LT-11","Incorrect password"],
["08:23:48","akim","10.20.4.51","LOGIN_SUCCESS","SUCCESS","ENG-LT-11","Successful sign-in after one failed attempt"],
["08:28:15","tnguyen","10.20.4.39","FILE_ACCESS","SUCCESS","Shipping_Log.csv","Read file from operations share"],
["08:31:02","jsmith","10.20.4.27","LOGOUT","SUCCESS","SALES-LT-09","User signed out of managed workstation"],
["08:35:44","mgarcia","10.20.4.18","FILE_ACCESS","SUCCESS","Leave_Calendar.xlsx","Read file from HR share"],
["08:39:17","svc_backup","10.20.1.12","SERVICE_AUTH","SUCCESS","backup01","Scheduled service authentication"],
["08:42:08","rpatel","10.20.4.22","EMAIL_SEND","SUCCESS","mail","Message sent to external vendor"],
["08:47:21","jsmith","203.0.113.77","LOGIN_FAILURE","FAILURE","cloud-idp","Password authentication failed"],
["08:47:39","jsmith","203.0.113.77","LOGIN_FAILURE","FAILURE","cloud-idp","Password authentication failed"],
["08:48:06","jsmith","203.0.113.77","LOGIN_SUCCESS","SUCCESS","cloud-idp","Interactive cloud sign-in; unmanaged client"],
["08:49:17","jsmith","203.0.113.77","MFA_CHANGE","SUCCESS","identity","New authentication method registered"],
["08:50:12","akim","10.20.4.51","FILE_ACCESS","SUCCESS","Design_Spec.docx","Read file from engineering share"],
["08:52:31","jsmith","203.0.113.77","MAIL_RULE_CREATE","SUCCESS","mail","New inbox rule created: forward matching messages"],
["08:54:09","mgarcia","10.20.4.18","LOGIN_SUCCESS","SUCCESS","HR-APP","SSO to HR application"],
["08:56:44","jsmith","203.0.113.77","FILE_ACCESS","SUCCESS","Client_Pricing.xlsx","Downloaded file from cloud storage"],
["08:58:13","rpatel","10.20.4.22","LOGOUT","SUCCESS","FIN-LT-07","User signed out"],
["09:01:13","mgarcia","10.20.4.18","LOGOUT","SUCCESS","HR-LT-14","User signed out"],
["09:03:27","tnguyen","10.20.4.39","EMAIL_READ","SUCCESS","mail","Mailbox activity from managed workstation"],
["09:05:55","jsmith","203.0.113.77","EMAIL_READ","SUCCESS","mail","Mailbox activity from cloud session"],
["09:08:42","svc_backup","10.20.1.12","FILE_ACCESS","SUCCESS","backup-target","Scheduled backup operation"],
["09:11:06","akim","10.20.4.51","EMAIL_SEND","SUCCESS","mail","Message sent to internal recipient"],
["09:14:22","tnguyen","10.20.4.39","LOGOUT","SUCCESS","OPS-LT-03","User signed out"],
["09:18:40","rpatel","10.20.4.22","LOGIN_SUCCESS","SUCCESS","FIN-LT-07","User resumed workstation session"],
["09:21:03","mgarcia","10.20.4.18","LOGIN_SUCCESS","SUCCESS","HR-LT-14","User resumed workstation session"],
["09:24:51","jsmith","203.0.113.77","LOGOUT","SUCCESS","cloud-idp","Cloud session ended"],
["09:28:36","svc_patch","10.20.1.20","SERVICE_AUTH","SUCCESS","patch01","Scheduled service authentication"],
["09:31:19","akim","10.20.4.51","LOGOUT","SUCCESS","ENG-LT-11","User signed out"],
["09:34:48","tnguyen","10.20.4.39","LOGIN_SUCCESS","SUCCESS","OPS-LT-03","User resumed workstation session"],
["09:38:10","svc_backup","10.20.1.12","SERVICE_AUTH","SUCCESS","backup01","Scheduled service authentication"]
].map((x,i)=>({id:"EVT-"+String(i+1).padStart(3,"0"),time:x[0],user:x[1],ip:x[2],event:x[3],result:x[4],resource:x[5],details:x[6]})),
evidence:[
{id:"user",title:"User Interview",desc:"Ask the employee about expected activity and context.",content:"<h2>User Interview</h2><blockquote>“I stopped working around 8:30 this morning and did not sign in again. I did not add an MFA method, create a forwarding rule, or download Client_Pricing.xlsx.”</blockquote><p><b>Analyst reminder:</b> A user statement adds context. Correlate it with technical evidence.</p>"},
{id:"email",title:"Email Gateway",desc:"Review recent inbound messages and link activity.",content:"<h2>Email Gateway</h2><p><b>Previous day, 15:42</b> — Message received by jsmith: <i>Payroll Verification Required</i>.</p><p><b>15:49</b> — Secure web gateway recorded a visit from the user's workstation to the external link contained in that message.</p><p>The gateway record establishes delivery and link access; it does not show what the user entered on the destination page.</p>"},
{id:"identity",title:"Identity / MFA",desc:"Request additional identity-provider context.",content:"<h2>Identity / MFA Context</h2><p>The authentication method registered at 08:49 had not previously been associated with jsmith. The request occurred within the same cloud session established at 08:48.</p><p>No help-desk ticket for an MFA reset was open at the time.</p>"},
{id:"ip",title:"IP Intelligence",desc:"Check history and context for a source address.",content:"<h2>IP Intelligence</h2><p><b>203.0.113.77</b> has not previously been observed for jsmith in the available 30-day sign-in history.</p><p>The address is associated with hosted infrastructure rather than the client's corporate address space.</p><p><b>Reminder:</b> IP context supports investigation; it does not by itself prove malicious activity.</p>"},
{id:"endpoint",title:"Endpoint Activity",desc:"Check whether the managed workstation explains the activity.",content:"<h2>Endpoint Activity</h2><p>SALES-LT-09 remained online after jsmith's 08:31 logout. No interactive user session for jsmith was recorded on that endpoint between 08:31 and 09:30.</p><p>No malware alert was generated on the workstation during this interval.</p>"}
]};