/* Shared AP concept display and editorial enrichment crosswalk, checked 2026-09-27. */
(() => {
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const ap='https://apcentral.collegeboard.org/media/pdf/ap-cybersecurity-course-and-exam-description.pdf';
  const cisco='https://www.netacad.com/courses/introduction-to-cybersecurity?courseLang=en-US';
  const cyber='https://cyber.org/cybersecurity-1';
  const data={
    'U1-001':{
      title:'Suspicious website logins',topic:'1.2 · Suspicious Website Logins',page:42,
      objectives:[['1.2.A','Recognize password-attack warning signs.'],['1.2.B','Connect weak authentication to adversary opportunity.'],['1.2.C','Explain stronger authentication choices.']],
      definition:'An unfamiliar sign-in becomes more concerning when it forms a pattern with failures or unexpected account changes. Evaluate the pattern against the user’s baseline.',
      cards:[['OBSERVED · PROVES','What the records establish','The teaching timeline records failures, a successful authentication, and a new MFA method in that session.'],['SUPPORTS','What the pattern suggests','The unfamiliar session and account change support investigating unauthorized activity.'],['DOES NOT PROVE','Where certainty stops','A successful login does not identify the person using the account. These records do not establish how the credentials were obtained.'],['NEED','How to strengthen the claim','Correlate the user’s account of events, approved changes, device history, and identity-session details.'],['PROTECTION','Strengthen authentication','Use lengthy, unique credentials and MFA. For this incident, also review sessions, registered methods, and mailbox changes; changing a password alone may leave other work unfinished.']],
      terms:[['Authentication','Checking a claimed identity.'],['MFA','Identity verification using more than one factor type.'],['Baseline','Expected activity used for comparison.'],['Password attack','An attempt to obtain access by exploiting a password.'],['Session','An authenticated interaction that may outlast the initial sign-in.'],['Credential exposure','Credentials are revealed; later use is a separate claim.']],
      cisco:'Sections 2.2 (infiltration methods), 3.1 (device/network protection), and 3.4 (online privacy).',
      cyber:'Unit 1 — Foundations and Threats; Unit 9 — Securing Online Components.',
      transfer:'Explain why a password change, MFA review, and session revocation solve different problems. Cite one case observation for each proposed action.'
    },
    'U1-002':{
      title:'Evil twin',topic:'1.3 · Best Practices for Public Networks',page:44,
      objectives:[['1.3.B','Distinguish wireless attack mechanisms.'],['1.3.C','Choose protections for sensitive information on public connections.'],['1.3.A','Use case evidence to assess adversary capability and motive.']],
      definition:'An adversary-operated access point imitates a legitimate network name to encourage connections through the wrong network.',
      cards:[['OBSERVED · PROVES','What the records establish','The guided timeline records an unapproved BSSID, a near-match SSID, client association, a portal observation, and later login events.'],['SUPPORTS','What the pattern suggests','The wireless pattern supports an evil-twin hypothesis. Identity activity warrants a separate investigation of possible unauthorized access.'],['DOES NOT PROVE','Where certainty stops','The SOC’s portal observation does not prove form submission. The submission shown to the student establishes exposure only in the teaching scene; it does not explain the later login.'],['NEED','How to strengthen the claim','Correlate approved wireless inventory, endpoint or submission evidence, the employee’s statement, and identity-session activity.'],['PROTECTION','Verify before you trust','Check the intended network with a trusted source and weigh data sensitivity. A VPN protects its encrypted path, but cannot make a deceptive portal trustworthy or prevent RF interference.']],
      terms:[['Evil twin','A deceptive access point that imitates a legitimate network.'],['SSID','The network name advertised to users.'],['BSSID','An identifier for a wireless access-point interface.'],['Jamming','Radio interference used to disrupt wireless availability.'],['War driving','Collecting wireless-network observations while moving through an area.'],['VPN','An encrypted connection to a VPN service; it does not certify a portal’s legitimacy.']],
      cisco:'Sections 1.4 (adversaries), 2.2 (infiltration methods), and 3.1 (device/network protection).',
      cyber:'Unit 7 — Reconnaissance; Unit 8 — Network and System Threats.',
      transfer:'Contrast evil twin, jamming, and reconnaissance. Give one distinguishing observation and one suitable protection or investigative step for each.'
    },
    'U1-003':{
      title:'Social engineering and correlated threats',topic:'1.1 · Understanding Social Engineering',page:40,
      objectives:[['1.1.A–C','Recognize manipulation, explain its influence, and assess potential harm.'],['1.2.A','Interpret suspicious authentication indicators.'],['1.3.B–C','Assess wireless threats and protective choices.']],
      definition:'Social engineering manipulates decisions. In a mixed incident, distinguish the influence attempt, any credential exposure, and subsequent account activity before connecting them into an attack path.',
      cards:[['OBSERVED · PROVES','What the records establish','The teaching sources record a message-linked visit, a near-match network association, a portal, and a mailbox change in an unfamiliar session.'],['SUPPORTS','What the pattern suggests','The pressure in the message and portal supports a social-engineering interpretation; the sequence provides multiple exposure hypotheses.'],['DOES NOT PROVE','Where certainty stops','Timing alone does not identify which exposure caused a session. A folder listing is not proof that file contents were stolen.'],['NEED','How to strengthen the claim','Compare the message, authorized domains and access points, employee statements, and session-linked actions. Seek evidence for each proposed connection.'],['PROTECTION','Interrupt more than one pathway','Verify requests independently, strengthen authentication, and check wireless authorization. Review active sessions and mailbox changes separately from the suspected initial lure.']],
      terms:[['Social engineering','Manipulating a person into an action that helps an adversary.'],['Urgency','Pressure to act before taking time to verify.'],['Intimidation','Pressure based on a threatened negative consequence.'],['Phishing','A deceptive message intended to prompt disclosure or another harmful action.'],['Correlation','Events are associated; this alone does not establish cause.'],['Exfiltration','Data is transferred out without authorization; a listing alone does not demonstrate it.']],
      cisco:'Sections 2.1 (attack analysis), 2.2 (infiltration methods), and 4.2 (behavior-based defense).',
      cyber:'Unit 2 — The Human Factor; Unit 8 — Network and System Threats; Unit 9 — Securing Online Components.',
      transfer:'Draw two possible paths to the suspicious session. Mark every link as established, supported, or unresolved, then name the source that would best distinguish the paths.'
    }
  };
  function reference(id){const d=data[id];if(!d)return '';return `<section class="learning-reference" aria-label="Lesson quick reference"><h3>Lesson quick reference</h3><p>${esc(d.topic)} · <strong>PROVES → SUPPORTS → NEED</strong></p><dl>${d.terms.map(([term,meaning])=>`<div><dt>${esc(term)}</dt><dd>${esc(meaning)}</dd></div>`).join('')}</dl><p class="learning-note">Concept reminders guide your reasoning; use the case’s actual sources to support your response.</p></section>`}
  function lens(id){const d=data[id];return `<article class="ap-lesson"><span class="concept">AP CYBERSECURITY · ${esc(d.topic)}</span><h2>${esc(d.title)}</h2><p class="definition">${esc(d.definition)}</p><section class="learning-alignment"><h3>College Board curriculum connection</h3><ul>${d.objectives.map(([code,text])=>`<li><strong>${esc(code)}</strong> · ${esc(text)}</li>`).join('')}</ul><a href="${ap}#page=${d.page}" target="_blank" rel="noopener noreferrer">View the College Board course framework ↗</a><p>Objective summaries are paraphrased. The evidence sections below apply them to this teaching scenario; they are not an official College Board scoring guide.</p></section><div class="evidence-cards">${d.cards.map((c,i)=>`<section class="evidence-card ${i===4?'protection':''}"><b>${c[0]}</b><h3>${c[1]}</h3><p>${esc(c[2])}</p></section>`).join('')}</div><p class="reasoning-strip"><strong>PROVES → SUPPORTS → NEED</strong><br>State the observation. Qualify the interpretation. Name the missing evidence.</p>${reference(id)}</article>`}
  function enrichment(id){const d=data[id];if(!d)return '';return `<section class="learning-enrichment" aria-label="Continue learning"><h3>Go deeper · enrichment and reinforcement</h3><p>Choose a resource, then return to the transfer challenge. These are Ironcrest’s topic matches to public course outlines, not provider-endorsed equivalencies.</p><div class="learning-resourcegrid"><article><h4>Cisco Networking Academy</h4><p><strong>Introduction to Cybersecurity</strong></p><p>${esc(d.cisco)}</p><a href="${cisco}" target="_blank" rel="noopener noreferrer">Open Cisco course and section outline ↗</a><p class="learning-note">Find the listed sections after signing in or enrolling.</p></article><article><h4>CYBER.ORG</h4><p><strong>Cybersecurity 1</strong></p><p>${esc(d.cyber)}</p><a href="${cyber}" target="_blank" rel="noopener noreferrer">Open CYBER.ORG course and unit outline ↗</a><p class="learning-note">Ask your teacher for the matching lessons in CYBERPortal. Public links show the unit outline; lesson access may require an account.</p></article></div><h4>Transfer challenge</h4><p>${esc(d.transfer)}</p><p class="learning-note">Revisit your explanation with what you learned. Editing the Final FRQ returns it to draft until you record it again.</p></section>`}
  window.IRONCREST_LEARNING={data,lens,reference,enrichment};
})();
