/* Unit 1 activity library. Teaching scenes are separate from case evidence. */
(() => {
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const catalog=[
    {id:'U1-001',name:'Possible Account Compromise',theme:'Identity & account security',description:'Follow a suspicious sign-in from an ordinary workday to post-login activity. Learn why a successful login is only part of the story.',icon:'01',packet:'account-v1'},
    {id:'U1-002',name:'Signal Lost',theme:'Public networks & wireless threats',description:'Experience a deceptive Wi-Fi connection, then investigate interference, unfamiliar access points, and identity clues.',icon:'02',packet:'signal-lost-v1'},
    {id:'U1-003',name:'Chain Reaction',theme:'Social engineering & incident correlation',description:'Follow a message and a near-match network. Decide which links in a possible attack chain the evidence actually supports.',icon:'03',packet:'chain-v1'}
  ];
  const read=key=>{try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}};
  function status(item){const draft=read('ironcrest-frq-'+item.packet);if(draft?.recordedAt&&draft.reviewed)return 'Final FRQ recorded';if(draft&&Object.values(draft.answers||{}).some(x=>String(x).trim()))return 'FRQ in progress';const state=read('ironcrest-'+item.id.toLowerCase());return state?'Investigation started':'Ready to start'}
  function landing(host,start){
    host.innerHTML=`<section class="unit-hero"><div><span class="unit-eyebrow">IRONCREST CYBER PARTNERS · UNIT 1</span><h1>Your next case starts here.</h1><p>Experience the incident. Learn the concept. Investigate as a defender. Finish with an evidence-based FRQ.</p></div><div class="unit-count"><strong>03</strong><span>available exercises</span></div></section><section aria-label="Unit 1 exercises"><div class="unit-sectionhead"><h2>Choose your assignment</h2><p>Follow the sequence, or return directly to a case you have started.</p></div><div class="unit-grid">${catalog.map(item=>`<article class="unit-card"><div class="unit-cardtop"><span>${item.icon} / UNIT 1</span><span class="unit-status">${status(item)}</span></div><p class="unit-theme">${item.theme}</p><h3>${item.name}</h3><p>${item.description}</p><ul><li>7 guided stages</li><li>Defender investigation · 3 evidence credits</li><li>Final FRQ · saved in this browser</li></ul><div class="unit-cardactions"><button data-unit-start="${item.id}">Start guided experience →</button><button class="unit-secondary" data-unit-case="${item.id}">Open case briefing</button></div></article>`).join('')}</div></section>${window.IRONCREST_STORY.coverage}<section class="unit-how"><h2>From experience to evidence</h2><ol><li><b>Experience</b><span>See one perspective at a time.</span></li><li><b>Investigate</b><span>Accept the case. Inspect records and test your questions.</span></li><li><b>Submit</b><span>Complete the Final FRQ, then copy it to your class submission system.</span></li></ol><p>Practice skills: Analyze Risk · Mitigate Risk · Detect Attacks. Final FRQs emphasize Mitigate Risk and Detect Attacks, with an Analyze Risk extension. Recorded completion is not an automatic score.</p></section>`;
    host.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.unitStart)start(b.dataset.unitStart,false);if(b.dataset.unitCase)start(b.dataset.unitCase,true)};
  }
  const steps=['Baseline','Adversary','Employee','Exposure','SOC','AP lens','Replay'];
  const lessons={
    'U1-001':[
      {view:'Employee workstation',title:'Start with normal.',task:'Find the expected sign-in pattern.',look:'Device ownership, time, and network context.',action:'Choose the strongest baseline comparison.',next:'Observe the adversary’s objective →',surface:'desktop',heading:'Cedar Works · CW-LT-08',lines:['Teaching vignette · separate from the case you will investigate','09:00 · mchen signs in from managed laptop CW-LT-08.','09:02 · Approved MFA method completes the sign-in.','Normal activity uses the company network and managed device.'],question:'Which comparison is most useful for a later alert?',choices:['Compare the device, source, and activity with this baseline.','Assume every successful login is legitimate.','Treat every failed password as a confirmed attack.'],answer:0,feedback:'A baseline supplies context. A difference merits investigation; it does not establish an attacker by itself.'},
      {view:'Adversary perspective',title:'The objective is continued access.',task:'Distinguish an adversary’s objective from defender evidence.',look:'Access to an account can enable changes and data access.',action:'Identify what the SOC still needs to observe.',next:'Switch to the employee →',surface:'terminal',heading:'Scenario director · adversary objective',lines:['Fictional, non-operational teaching view','An adversary wants access to a work account and its mailbox.','The director reveals intent, not a log entry.','No attack commands or live services are used.'],question:'Can the defender cite this objective as case evidence?',choices:['Yes, because students saw it.','No. Defender conclusions need observable records or collected evidence.'],answer:1,feedback:'A teaching camera can reveal intent. The SOC must support its claim with its own sources.'},
      {view:'Employee inbox',title:'A routine-looking request.',task:'Inspect the sign-in request before choosing a response.',look:'The message asks for a work password through an unfamiliar link.',action:'Choose an appropriate verification step.',next:'Observe the fictional outcome →',surface:'mail',heading:'Inbox · Access review requested',lines:['From: Account Services <access@cedar-review.example>','Message: Review your work account using this link today.','The organization’s known sign-in site is login.cedar.example.','This is a fictional message. No links are active.'],question:'What should the employee do?',choices:['Use the familiar display name as proof.','Enter a password to see whether the page works.','Open the known company sign-in route and independently verify the request.'],answer:2,feedback:'Independent verification avoids trusting the message’s own destination. The next scene follows a fictional employee who did enter credentials.'},
      {view:'Employee outcome',title:'Exposure has a specific meaning.',task:'Read the director’s explicit submission event.',look:'Submission and later account use are separate claims.',action:'Select what this event establishes.',next:'Inspect defender telemetry →',surface:'desktop',heading:'Training receipt · fictional event',lines:['09:07 · The fictional employee submits a work password to the untrusted page.','This event is shown only to explain exposure.','No actual credentials are entered or transmitted.','Later account use still needs evidence.'],question:'What does this receipt establish?',choices:['The employee’s credentials were exposed in this vignette.','The attacker definitely downloaded every file.','The endpoint must contain malware.'],answer:0,feedback:'Explicit submission establishes exposure in the teaching scene. It does not establish the actor or consequences of later activity.'},
      {view:'SOC analyst',title:'Look beyond the successful login.',task:'Correlate the identity events.',look:'The unfamiliar session changes an authentication method.',action:'Select the claim these records support.',next:'Reveal the AP lens →',surface:'siem',heading:'Identity timeline · defender snapshot',lines:['09:10:02 · LOGIN_FAILURE · unfamiliar browser · mchen','09:10:21 · LOGIN_SUCCESS · unfamiliar browser · mchen','09:11:07 · MFA_CHANGE · new method registered in that session','No form-submission record is available to the SOC.'],question:'Which conclusion is defensible?',choices:['A success proves the employee approved the session.','Post-login changes strengthen concern; verify authorization and the source of access.','The timeline proves which website stole the password.'],answer:1,feedback:'The sequence supports investigation of unauthorized activity. Correlate session details and user context before attributing cause.'},
      {view:'AP Exam Lens',title:'Detect the pattern. Qualify the claim.',task:'Connect evidence to a security conclusion.',look:'PROVES: recorded events. SUPPORTS: unauthorized-access hypothesis. NEED: authorization and session context.',action:'Choose the response that addresses ongoing access.',next:'Begin defender-only replay →',surface:'lesson',heading:'Identity compromise · mitigation boundaries',lines:['Failed attempts alone do not establish access.','Successful authentication records access, not the human actor.','An unapproved MFA change or forwarding rule strengthens an unauthorized-activity hypothesis.','Contain active sessions, review authentication methods and mailbox rules, and preserve evidence.'],question:'Why might a password reset alone be insufficient?',choices:['Existing sessions or unauthorized account changes may still need separate containment.','Passwords never matter.'],answer:0,feedback:'Mitigation should address the observed activity and persistence, not only the initial credential.'},
      {view:'Defender-only replay',title:'Accept your identity investigation.',task:'Investigate Possible Account Compromise using only its case sources.',look:'The case has its own accounts, records, and evidence locker.',action:'Review the briefing and accept your assignment.',surface:'lesson',heading:'U1-001 · Possible Account Compromise',lines:['The teaching vignette is over. Its facts are not evidence for this case.','Inspect telemetry → request evidence → build your case file.','Complete the Final FRQ after investigating.','Your saved response is ready to copy for teacher review.']}
    ],
    'U1-003':[
      {view:'Employee workstation',title:'Two trusted routes.',task:'Establish the approved sign-in and Wi-Fi routes.',look:'Exact names and independent verification matter.',action:'Choose the baseline to preserve.',next:'Observe the pressure tactic →',surface:'desktop',heading:'Lakeside Group · travel briefing',lines:['Teaching vignette · separate from Chain Reaction','Approved sign-in: login.lakeside.example','Venue notice: Lakeside-Guest','A matching name is a starting comparison, not a guarantee of authorization.'],question:'What helps evaluate a later sign-in request?',choices:['The logo alone.','Compare with independently obtained sign-in and network information.'],answer:1,feedback:'A trusted baseline supports comparison. Branding and signal strength do not establish ownership.'},
      {view:'Adversary perspective',title:'Make the decision feel urgent.',task:'Identify the pressure built into a fictional lure.',look:'The text links immediate action to avoiding a penalty.',action:'Identify the manipulation tactic.',next:'Switch to the employee inbox →',surface:'terminal',heading:'Scenario director · lure preview',lines:['Fictional, non-operational teaching view','Payroll access expires in ten minutes. Verify immediately.','The adversary hopes urgency will replace independent verification.','The director’s account of intent is not defender evidence.'],question:'Which tactic is visible in the wording?',choices:['Urgency and a threatened negative consequence.','A technical proof that the sender is legitimate.'],answer:0,feedback:'The wording uses urgency and a threatened consequence. That identifies a tactic, not whether anyone complied.'},
      {view:'Employee inbox',title:'A second opportunity to verify.',task:'Choose how to handle an unexpected benefits message.',look:'The destination differs from the approved sign-in route.',action:'Select the safer next step.',next:'Observe two exposure opportunities →',surface:'mail',heading:'Inbox · Benefits verification',lines:['From: Benefits Desk <benefits@lakeside-check.example>','Subject: Verify before payroll access expires','Requested action: enter work credentials through the message link.','All addresses are fictional; no live links are provided.'],question:'What should the employee do?',choices:['Use the message link because the display name looks familiar.','Use the known company route or contact the benefits team independently.'],answer:1,feedback:'Independent verification checks the request without relying on its potentially deceptive route. Next, follow the fictional employee’s risky choices.'},
      {view:'Employee outcome',title:'Two exposures are not one proven cause.',task:'Read the explicit training events.',look:'Both submission opportunities precede the identity activity.',action:'Separate exposure from attribution.',next:'Inspect the SOC’s narrower view →',surface:'desktop',heading:'Training receipt · two fictional submissions',lines:['10:05 · Employee submits credentials to the benefits imitation page.','10:09 · Employee submits credentials to a portal on Lakeside_Guest.','Both events are fictional director-view receipts.','No real credentials or network connections are used.'],question:'Can these events identify which exposure caused a later session?',choices:['Yes, the most recent event must be the cause.','No. Establishing a causal path requires additional correlation.'],answer:1,feedback:'Both are exposure opportunities. Timing alone cannot determine which, if either, enabled a later session.'},
      {view:'SOC analyst',title:'Correlate without inventing a chain.',task:'Compare message, wireless, and identity observations.',look:'The defender does not have the training receipts.',action:'Select the supported conclusion.',next:'Reveal the AP lens →',surface:'siem',heading:'Cross-source timeline · defender snapshot',lines:['10:04 · Gateway records a visit to lakeside-check.example.','10:08 · Endpoint associates with Lakeside_Guest.','10:09 · Sensor observes a sign-in portal; no form telemetry.','10:14 · Unfamiliar cloud session creates a mailbox rule.'],question:'What do these sources support?',choices:['Investigate related exposure opportunities and suspicious account activity; the causal path remains unproven.','The wireless portal definitely caused the mailbox rule.'],answer:0,feedback:'The records support several hypotheses. User statements, approved inventories, and session detail can strengthen or challenge each link.'},
      {view:'AP Exam Lens',title:'Each arrow needs evidence.',task:'Explain how evidence supports a link in an incident narrative.',look:'Social engineering, exposure, authentication, and post-login actions are distinct.',action:'Choose a precise claim.',next:'Begin defender-only replay →',surface:'lesson',heading:'Multi-source analysis · PROVES / SUPPORTS / NEED',lines:['Message language can show urgency or impersonation indicators.','A site visit is not a credential-submission record.','A near-match SSID needs comparison with authorized infrastructure.','A mailbox-rule event is not proof of what information was read or stolen.'],question:'Which statement keeps the evidence boundary?',choices:['A file listing proves all documents were exfiltrated.','A file listing records metadata access; file-content access needs its own evidence.'],answer:1,feedback:'Describe the logged action precisely. Do not upgrade a listing into an unobserved download or exfiltration.'},
      {view:'Defender-only replay',title:'Investigate Chain Reaction.',task:'Reconstruct the case using only its defender sources.',look:'Keep possible pathways separate until evidence supports a connection.',action:'Review the briefing and accept your assignment.',surface:'lesson',heading:'U1-003 · Chain Reaction',lines:['Leave the teaching vignette behind. Chain Reaction has its own evidence.','Inspect message, wireless, web, and identity observations.','Use evidence credits to test uncertain links in your explanation.','Finish by submitting the Final FRQ for teacher review.']}
    ]
  };
  function lesson(host,id,openCase,home){
    const sequence=lessons[id];let index=0,exposureViewed=false;const passed=new Set();
    function render(){const s=sequence[index];host.innerHTML=`<button class="unit-secondary" data-home>← All exercises</button><div class="unit-lessonhead"><p class="unit-eyebrow">UNIT 1 · GUIDED EXPERIENCE · ${esc(id)}</p><h1>${esc(catalog.find(x=>x.id===id).name)}</h1><div class="story-context"><strong>Your situation</strong><p>${esc(window.IRONCREST_STORY.stories[id].intro)}</p><strong>Your objective</strong><p>${esc(window.IRONCREST_STORY.stories[id].goal)}</p></div></div><ol class="journey" aria-label="Seven-stage learning journey">${steps.map((name,i)=>`<li class="${i===index?'active':i<index?'done':''}" ${i===index?'aria-current="step"':''}><span>${i+1}</span>${name}</li>`).join('')}</ol><div class="mission-layout"><section class="mission-control" aria-label="Mission Control"><b class="mission-brand">MISSION CONTROL / YOUR TASK</b><p>STEP ${index+1} OF 7</p><h2>${esc(s.view)}</h2><p class="unit-task">${esc(s.task)}</p><dl><dt>Look for</dt><dd>${esc(s.look)}</dd><dt>Your action</dt><dd>${esc(s.action)}</dd><dt>Up next</dt><dd>${index===6?'Investigate the case, then submit the Final FRQ.':esc(s.next.replace(' →',''))}</dd></dl>${index<6?`<button data-next ${passed.has(index)?'':'disabled'}>${esc(s.next)}</button>`:''}<button class="unit-secondary" data-back ${index===0?'disabled':''}>← Back</button></section><section class="stage-column"><p class="unit-eyebrow">FICTIONAL TRAINING ENVIRONMENT · ${esc(s.view)}</p><h2 tabindex="-1" id="unitStageTitle">${esc(s.title)}</h2>${index===5?window.IRONCREST_LEARNING.lens(id):window.IRONCREST_STORY.render(id,index,exposureViewed)}${index<6?`<section class="reflection"><h3>${esc(s.question)}</h3><div class="choice-list">${s.choices.map((c,i)=>`<button data-answer="${i}" ${index===3&&!exposureViewed?'disabled':''}>${esc(c)}</button>`).join('')}</div><p role="status" class="unit-feedback">${passed.has(index)?esc(s.feedback):''}</p><button class="story-bottomnext" data-next ${passed.has(index)?'':'disabled'}>${esc(s.next)}</button></section>`:'<section class="reflection"><h3>Accept case → Investigate → Submit Final FRQ</h3><button data-open>Review case briefing →</button></section>'}</section></div>`;
      host.onclick=e=>{const b=e.target.closest('button');if(!b||b.disabled)return;if(b.hasAttribute('data-story-submit')){exposureViewed=true;render();host.querySelector('[data-answer]').focus()}else if(b.hasAttribute('data-home'))home();else if(b.hasAttribute('data-open'))openCase(id);else if(b.hasAttribute('data-next')){index++;render();host.querySelector('#unitStageTitle').focus()}else if(b.hasAttribute('data-back')){index--;render()}else if(b.hasAttribute('data-answer')){const correct=Number(b.dataset.answer)===s.answer;const feedback=host.querySelector('.unit-feedback');feedback.textContent=correct?'ACTION RECORDED — '+s.feedback:'STOP & THINK — Revisit the observations. Choose the claim that stays within the available evidence.';if(correct)passed.add(index);else passed.delete(index);host.querySelectorAll('[data-next]').forEach(x=>x.disabled=!correct);host.querySelectorAll('[data-answer]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))}};
    }render();window.scrollTo(0,0);
  }
  const q=(id,verb,prompt,criterion)=>({id,label:id[0]+'('+id.slice(1)+')',verb,prompt,criterion,...(verb==='Write'?{command:true}:{})});
  function packet(c,state){
    const chain=c.id==='U1-003',item=catalog.find(x=>x.id===c.id);
    const parts=chain?[
      {id:'A',title:'Trace the observable sequence',skill:'Detect Attacks',questions:[q('Ai','Identify','one social-engineering indicator in the message or portal records in Source 1. Cite the record ID.','A specific observed indicator is identified with an accurate citation.'),q('Aii','Describe','two observations from different source types that support investigating related threats. Cite record IDs; do not claim that sequence alone establishes causation.','Two accurate observations from distinct source types are connected to a defensible investigative hypothesis.')]},
      {id:'B',title:'Evaluate competing explanations',skill:'Detect Attacks',questions:[q('Bi','Determine','whether the available evidence establishes which credential-exposure opportunity caused the external session. Support your conclusion with Sources 1 and any unlocked Source 2 evidence.','The conclusion respects limits on causal attribution and uses only available sources.'),q('Bii','Explain','why the mailbox-rule creation and folder-listing events do not by themselves prove that file contents were stolen. Identify one additional source that would test that claim.','The explanation distinguishes logged actions from content access or exfiltration and proposes a relevant source.')]},
      {id:'C',title:'Interrupt the incident pathways',skill:'Mitigate Risk',questions:[q('Ci','Explain','a specific change to Source 3, line 1 that reduces social-engineering risk, including how the change works.','An actionable policy modification is connected to independent verification and the relevant risk.'),q('Cii','Describe','two response actions addressing different observed risks: one for the suspicious account session and one for the unauthorized-network hypothesis. State a limitation of each.','Each action matches a distinct risk and includes an accurate limitation without overclaiming prevention.')]},
      {id:'D',title:'Protect the collected evidence',skill:'Mitigate Risk',questions:[q('Di','Write','one command using Source 4 to give only the owner read and write permission to incident-notes.txt, with no execute permission. Do not execute it.','A valid chmod command sets the regular file to owner read/write only (600 or an equivalent exact symbolic mode).'),q('Dii','Explain','one security benefit of D(i) and why this file-permission change does not contain the suspicious cloud session.','The explanation connects local access restrictions to confidentiality and distinguishes file permissions from cloud-session containment.')]} 
    ]:[
      {id:'A',title:'Detect suspicious account activity',skill:'Detect Attacks',questions:[q('Ai','Identify','the account and unfamiliar source address associated with the clustered login failures followed by a success in Source 1. Cite one record ID.','The account, source address, and relevant citation are accurate.'),q('Aii','Describe','two post-login actions that strengthen concern about the session, using record IDs and explaining what each records.','Two actual post-login actions are accurately described; failed attempts alone do not satisfy this criterion.')]},
      {id:'B',title:'Assess authorization and cause',skill:'Detect Attacks',questions:[q('Bi','Determine','what your available sources support about unauthorized account activity. Distinguish an observed login from the identity of the person using it.','The conclusion weighs available evidence without claiming a successful login alone identifies the human actor.'),q('Bii','Explain','why a message delivery or link visit does not prove credential submission. Identify one additional source that could test the initial-access hypothesis.','The explanation distinguishes delivery/visit from submission and identifies relevant missing evidence.')]},
      {id:'C',title:'Contain access and persistence',skill:'Mitigate Risk',questions:[q('Ci','Explain','how to modify Source 3, line 1 to respond to the observed authentication-method and mailbox changes. Include a specific control and why it helps.','A policy modification addresses an observed post-login risk and explains the security benefit.'),q('Cii','Describe','one way to verify that containment worked and one limitation of relying only on a password reset.','The verification is observable and relevant; the limitation accounts for active sessions or remaining unauthorized changes.')]},
      {id:'D',title:'Apply a scoped configuration change',skill:'Mitigate Risk',questions:[q('Di','Write','one Windows command using Source 4 to disable only the local temp-review account. Do not execute it.','The command targets temp-review with /active:no and does not target a domain or other account.'),q('Dii','Explain','why disabling this local account does not revoke jsmith’s cloud sessions, and identify a separate response needed for those sessions.','The explanation distinguishes local and cloud identities and specifies cloud-session containment.')]}
    ];
    return {id:item.packet,title:c.title+' · Final FRQ',intro:'After investigating '+c.title+', complete Parts A–D as your final activity submission. Use case records and evidence you unlocked; teaching-vignette events are not case evidence.',sources:[
      {id:'1',title:c.telemetryName+' · case records',lines:c.records.map(r=>`${r.id} · ${r.time} · ${r.user} · ${r.ip} · ${r.event} · ${r.result} · ${r.resource} · ${r.details}`)},
      {id:'2',title:'Evidence Locker · only your unlocked sources',evidence:c.evidence.map((e,i)=>({...e,ref:'2.'+(i+1)})).filter(e=>state.unlocked.includes(e.id))},
      {id:'3',title:'Response policy · assessment stimulus',lines:chain?['Employees may verify urgent benefits messages using the link in the message.','Responders must preserve relevant evidence and document authorized containment actions.','Employee credentials and HR/payroll information require protection from unauthorized access.','These rules are a fictional assessment stimulus; evaluate whether they are sufficient.']:['After a suspicious account alert, reset the password and immediately close the incident.','Responders must preserve relevant identity and mailbox logs before authorized remediation.','Client pricing and work-account credentials require protection from unauthorized disclosure.','These rules are a fictional assessment stimulus; evaluate whether they are sufficient.']},
      {id:'4',title:'Hypothetical configuration and command reference',reference:true,lines:chain?['A Linux triage workstation contains a regular file incident-notes.txt owned by the analyst. This is an assessment exercise, not an additional incident finding.','Current mode: 644. No extended ACLs are present. The analyst is authorized to change this file’s mode.','Reference: chmod MODE FILE. Three octal digits set owner, group, and other permissions. Read = 4, write = 2, execute = 1; add values within each digit.','Target: owner read/write, group no access, others no access. Permissions do not encrypt the file or revoke a cloud session.']:['An authorized Windows 11 lab workstation has a local account named temp-review. This hypothetical snapshot is not an additional incident finding.','The local account is active. The exercise requires disabling that account only; retain every other account.','Reference: net user USERNAME /active:{yes|no}. Choose one value, without braces. Without /domain this targets the local computer.','This operation does not revoke cloud tokens, remove mailbox rules, or disable the cloud account jsmith.']}
    ],parts,extension:{id:'E',title:'Risk-analysis extension',skill:'Analyze Risk · course extension',questions:[q('Ei','Identify','one sensitive asset and one plausible impact supported by the case context. Distinguish potential impact from a confirmed outcome.','A specific asset and plausible impact are identified without asserting unobserved harm.'),q('Eii','Explain','which risk you would prioritize using likelihood, potential impact, and a specific case observation. State one uncertainty that could change that priority.','The prioritization connects evidence to likelihood and impact and identifies a meaningful uncertainty.')]}};
  }
  window.IRONCREST_UNIT1={catalog,lessons,landing,lesson,packet};
})();
