(()=>{const CASES=window.IRONCREST_CASES,$=s=>document.querySelector(s);let C=null,state=null,KEY="",selected=null,pendingEvidence=null,editingAssessment=false;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const showModal=html=>{$("#modalBody").innerHTML=html;$("#modal").classList.remove("hidden")},closeModal=()=>$("#modal").classList.add("hidden");
function defaults(c){return{credits:c.credits||3,unlocked:[],timeline:[],notes:"",evidenceQuestions:{},evidenceAdded:[],team:c.roles[0],assessment:null}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function loadState(){KEY="ironcrest-"+C.id.toLowerCase();state=Object.assign(defaults(C),JSON.parse(localStorage.getItem(KEY)||"{}"));state.timeline=(state.timeline||[]).map(x=>x&&x.type?x:{type:"legacy",time:(x&&x.time)||"—",title:"Migrated Finding",source:"Legacy case file",observation:(x&&x.text)||"Imported finding."});save()}
function caseState(c){try{return JSON.parse(localStorage.getItem("ironcrest-"+c.id.toLowerCase())||"{}")}catch(e){return{}}}



const RANGE_STEPS=[
 {perspective:'Employee view',title:'Know the network before you join.',task:'Find the exact approved Wi-Fi name.',look:'Compare the workplace notice with the network marked Connected.',do:'Select the approved SSID in the checkpoint below the laptop.',after:'You will watch the attacker’s simulated wireless observations.',next:'Watch the attacker scan →',question:'Which SSID is approved by the venue?',choices:[['baseline','Bellweather-Guest'],['near','Bellweather_Guest'],['cafe','Cafe-Free-WiFi']],answer:'baseline',feedback:'The approved SSID is Bellweather-Guest, with a dash. Establishing this baseline lets you recognize a later change.'},
 {perspective:'Attacker view',title:'A familiar name becomes a target.',task:'Examine the simulated wireless scan.',look:'Network names, BSSIDs, channels and signal strength are visible. Passwords are not.',do:'Identify what the scan allows the attacker to learn.',after:'The camera switches to the employee’s Wi-Fi decision.',next:'Switch to employee view →',question:'What can the attacker learn from these observations?',choices:[['ssid','Network names, identifiers, channels and signal strength'],['password','Employee passwords and private files'],['trust','Which network is safe to trust']],answer:'ssid',feedback:'The scan reveals wireless characteristics, not passwords or private files. The attacker chooses a near-match SSID: Bellweather_Guest. This teaching view is not evidence the SOC automatically has.'},
 {perspective:'Employee view',title:'Two familiar names. One decision.',task:'Examine the available Wi-Fi networks.',look:'Compare each SSID with the approved name: Bellweather-Guest. Signal strength is not a trust signal.',do:'Select the network you think the employee would connect to.',after:'Your choice is recorded. Then follow the fictional employee’s near-match connection.',next:'Follow the employee’s connection →'},
 {perspective:'Employee · browser view',title:'The network asks for something sensitive.',task:'Inspect the captive portal, then submit the fictional training credentials.',look:'A familiar brand and a sign-in request are not proof that this portal is trustworthy.',do:'Use the prefilled, read-only training form. Then assess what submission establishes.',after:'You will see what the defender’s sensors recorded.',next:'See what the SOC detected →',question:'What does the simulated form submission establish?',choices:[['exposure','The fictional credentials were exposed to the portal'],['access','An attacker definitely used the account later'],['malware','The laptop was infected with malware']],answer:'exposure',feedback:'The explicit form-submission event establishes exposure in this simulation. Exposure alone does not prove later use of the account.'},
 {perspective:'SOC view',title:'What could the defender prove?',task:'Separate observed events from an explanation of those events.',look:'Correlate wireless and identity telemetry. No form-submission record is available to the SOC.',do:'Search or filter the timeline, then select the defensible claim below it.',after:'The AP Exam Lens names the mechanism and its evidence boundaries.',next:'Reveal the AP concept →',question:'You know what actually happened because you watched it. What could the SOC prove?',choices:[['supports','The logs record association, a portal observation and later login events; their causal link still needs evidence'],['portal','Seeing the portal proves credentials were submitted'],['cause','The successful login proves the evil twin caused account access']],answer:'supports',feedback:'The records establish the observed events. Together they support an impersonating access-point hypothesis and suspicious identity activity. They do not prove credential submission, who logged in, or the cause of that login.'},
 {perspective:'AP Exam Lens',title:'Connect the experience to the concept.',task:'Name the mechanism and keep the evidence boundary.',look:'Read OBSERVED, SUPPORTS, DOES NOT PROVE and PROTECTION.',do:'Check what a VPN can and cannot protect.',after:'Attacker and employee views disappear for the defender-only replay.',next:'Start defender-only replay →',question:'Which statement about a VPN is accurate?',choices:[['vpn','It encrypts traffic to the VPN operator, but does not make a fraudulent credential portal trustworthy'],['safe','It makes any captive portal safe to sign in to'],['jam','It prevents radio-frequency jamming']],answer:'vpn',feedback:'A VPN protects traffic on its encrypted path. It does not verify that a credential portal deserves your trust.'},
 {perspective:'Defender-only replay',title:'Detect it without seeing the attacker.',task:'Respond to a source-based, AP-style free-response task.',look:'Use the numbered source packet. Distinguish observed events from inferences and missing evidence.',do:'Complete Parts A–D using the task verbs, then check your evidence and record your response.',after:'Your response is recorded for teacher review. Continue to U1-002 · Signal Lost; completion is not an AP score.'}
];
const SOC_EVENTS=[
 {time:'08:38:12',source:'Inventory',kind:'wireless',text:'Approved guest SSID: Bellweather-Guest. BSSID A4:77:19:20:11:03; channel 6.'},
 {time:'08:40:36',source:'Wireless',kind:'wireless',text:'Near-match SSID Bellweather_Guest observed at −42 dBm; channel 6.',alert:true},
 {time:'08:40:44',source:'Inventory',kind:'wireless',text:'BSSID AA:91:7C:22:4F:10 is not in the venue’s approved access-point inventory.',alert:true},
 {time:'08:41:03',source:'Endpoint',kind:'wireless',text:'BW-LT-22 associated to Bellweather_Guest / AA:91:7C:22:4F:10.'},
 {time:'08:41:19',source:'Web sensor',kind:'wireless',text:'Captive portal observed: bellweather-guest.example/portal. No form-submission telemetry available.'},
 {time:'08:47:21',source:'Identity',kind:'identity',text:'LOGIN_FAILURE · jordan.lee · unfamiliar source 198.51.100.44.'},
 {time:'08:47:39',source:'Identity',kind:'identity',text:'LOGIN_FAILURE · jordan.lee · unfamiliar source 198.51.100.44.'},
 {time:'08:48:06',source:'Identity',kind:'identity',text:'LOGIN_SUCCESS · jordan.lee · unfamiliar source 198.51.100.44. Actor and cause unverified.'}
];
let rangeStep=0,portalSubmitted=false,networkChoice='',replayComplete=false;
const completedSteps=new Set();
function renderWorkspace(){renderRange()}
function rangeFeedback(message,ok=true){const box=$('#decisionFeedback');box.textContent=(ok?'ACTION RECORDED — ':'STOP & THINK — ')+message;box.className='action-feedback '+(ok?'correct':'incorrect')}
function updateRangeNavigation(){
 const next=$('#rangeNext');next.hidden=rangeStep===6;next.disabled=!completedSteps.has(rangeStep);next.textContent=RANGE_STEPS[rangeStep].next||'';
 $('#nextHint').textContent=rangeStep===6?'Complete Parts A–D and the evidence self-check to record your response.':completedSteps.has(rangeStep)?'Checkpoint complete. Move on when ready.':'Complete your task in the main view to unlock the next step.';
}
function osBar(title,linux=false){return '<div class="os-bar '+(linux?'linux-bar':'')+'"><span>'+title+'</span><span aria-hidden="true">−　□　×</span></div>'}
function taskbar(){return '<div class="win-taskbar"><span class="windows-logo" aria-label="Windows Start"><i></i><i></i><i></i><i></i></span><span>⌕ Search</span><span>▣</span><span>▰</span><span class="taskbar-time">Wi-Fi · 87%<br>'+(rangeStep===0?'08:38':rangeStep===2?'08:40':'08:41')+'</span></div>'}
function employeeView(){
 const decision=rangeStep===2;
 return '<div class="scene-surface">'+osBar('Bellweather Financial · BW-LT-22 · Windows 11')+'<div class="win-desktop"><div class="desktop-brand"><div class="brand-monogram">B</div><strong>Bellweather Financial</strong><span>Your workspace, wherever you work.</span><div class="baseline-note"><b>Venue Wi-Fi notice</b><p>Approved guest network</p><code>Bellweather-Guest</code><p>Verify the exact name with venue staff before connecting.</p></div></div><div class="wifi-card '+(decision?'task-target':'')+'"><div class="wifi-title"><span>Wi-Fi</span><span class="toggle-on">On</span></div><button class="wifi-network" data-network="approved" '+(!decision?'disabled':'')+'><span class="wifi-icon" aria-hidden="true">◉</span><span><strong>Bellweather-Guest</strong><small>'+(decision?'Available · Secured · −48 dBm':'Connected · Secured')+'</small></span></button>'+(decision?'<button class="wifi-network" data-network="rogue"><span class="wifi-icon" aria-hidden="true">◉</span><span><strong>Bellweather_Guest</strong><small>Open · Strong signal · −42 dBm</small></span></button>':'')+'<button class="wifi-network" data-network="cafe" '+(!decision?'disabled':'')+'><span class="wifi-icon" aria-hidden="true">◉</span><span><strong>Cafe-Free-WiFi</strong><small>Open · Weak signal · −72 dBm</small></span></button><hr><small>Network &amp; internet settings · simulation</small></div></div>'+taskbar()+'</div>';
}
function attackerView(){return '<div class="scene-surface">'+osBar('Linux security workstation · training observation viewer',true)+'<div class="linux-desktop"><div class="terminal-window"><div class="terminal-title">Terminal — wireless-observations.log</div><div class="terminal-body"><div class="prompt">analyst@range ~ / observations</div><div>08:39:12 · Recorded wireless observations loaded</div><div class="telemetry-scroll"><table class="scan-table"><thead><tr><th>SSID</th><th>BSSID</th><th>CH</th><th>SIGNAL</th></tr></thead><tbody><tr><td>Bellweather-Guest</td><td>A4:77:19:20:11:03</td><td>6</td><td>−48 dBm</td></tr><tr><td>Bellweather-Staff</td><td>8C:21:70:44:09:12</td><td>44</td><td>−61 dBm</td></tr><tr><td>Cafe-Free-WiFi</td><td>72:09:55:18:30:22</td><td>11</td><td>−72 dBm</td></tr></tbody></table></div><div class="terminal-notice">08:39:48 · Simulation director<br>Adversary selects a look-alike name:<br><strong>Bellweather_Guest</strong><br>Compare with approved: Bellweather-Guest</div><p class="teaching-label">Fictional observations only. This viewer does not execute commands or interact with wireless networks.</p></div></div></div></div>'}
function portalView(){return '<div class="scene-surface">'+osBar('Bellweather Financial · BW-LT-22 · Windows 11')+'<div class="win-desktop portal-desktop"><div class="portal-browser"><div class="browser-tabs">◉ Guest network sign-in　 ×</div><div class="address-row"><span aria-hidden="true">←　↻</span><code>bellweather-guest.example/portal</code></div><div class="portal-content"><div class="portal-brandline"><div class="brand-monogram">B</div><span>Bellweather Financial<br><small>Guest access</small></span></div>'+(portalSubmitted?'<div class="exposure-receipt" role="status"><h3>Training submission recorded</h3><p>The fictional credentials were exposed to this simulated portal.</p><p>The browser reported “Internet access restored.” That message does not establish trust.</p><b>Now answer the evidence checkpoint below.</b></div>':'<h3>Network access verification</h3><p>Your session has expired. Sign in with your company account to restore guest access.</p><label>Work email<input value="jordan.lee@bellweather.example" readonly autocomplete="off"></label><label>Password<input value="TrainingPassword!" type="password" readonly autocomplete="off"></label><button id="portalSubmit" class="portal-button task-target">Submit fictional training credentials →</button><small>Training simulation · read-only fictional credentials. No credentials are transmitted.</small>')+'</div></div>'+(portalSubmitted?'<div class="windows-notification" role="status"><small>Windows · Network status</small><strong>Connected to Bellweather_Guest</strong><span>Internet access restored · simulated notification</span></div>':'')+'</div>'+taskbar()+'</div>'}
function socView(){return '<div class="scene-surface siem"><div class="siem-top"><strong>Sentinel / Security operations</strong><span>Bellweather tenant · synthetic data</span></div><div class="siem-nav"><strong>Event timeline</strong><span>Wireless + Identity</span><span>09:00 snapshot</span></div><div class="siem-body"><div class="alert-summary"><span class="severity">High · investigate</span><strong>Unapproved access point + identity anomaly</strong></div><div class="siem-filters"><label>Search timeline<input id="socSearch" type="search" placeholder="SSID, BSSID, source or event"></label><label>Data source<select id="socFilter"><option value="all">All sources</option><option value="wireless">Wireless / endpoint</option><option value="identity">Identity</option></select></label></div><p id="socCount" class="event-count" aria-live="polite"></p><div id="socEvents" class="event-list"></div><div class="evidence-limit"><strong>Visibility boundary</strong><br>A portal observation is not a form-submission record. A login success is not proof of who used the account or how access was obtained.</div></div></div>'}
function renderSocEvents(){if(!$('#socEvents'))return;const q=$('#socSearch').value.toLowerCase(),filter=$('#socFilter').value;const events=SOC_EVENTS.filter(e=>(filter==='all'||e.kind===filter)&&[e.time,e.source,e.text].join(' ').toLowerCase().includes(q));$('#socCount').textContent=events.length+' of '+SOC_EVENTS.length+' events · 08:38–08:48';$('#socEvents').innerHTML=events.length?events.map(e=>'<div class="event-row '+(e.kind==='identity'?'identity':e.alert?'alert':'')+'"><time>'+e.time+'</time><span class="source">'+e.source+'</span><p>'+esc(e.text)+'</p></div>').join(''):'<div class="event-row">No matching events. Adjust your search or source filter.</div>'}
function apView(){return '<article class="ap-lesson"><span class="concept">AP CYBERSECURITY · TOPIC 1.3</span><h2>Evil twin</h2><p class="definition">An adversary-operated wireless access point uses an SSID similar or identical to a legitimate network.</p><div class="evidence-cards"><section class="evidence-card"><b>OBSERVED · PROVES</b><h3>What the records establish</h3><ul><li>A near-match SSID appeared on an unapproved BSSID.</li><li>The client associated to that access point.</li><li>A portal was observed; later login failures and a success were logged.</li></ul></section><section class="evidence-card"><b>SUPPORTS</b><h3>What the pattern suggests</h3><p>The combined wireless observations support an evil-twin classification. The identity sequence supports investigating possible unauthorized access.</p></section><section class="evidence-card"><b>DOES NOT PROVE</b><h3>Where certainty stops</h3><p>A fake portal does not prove credentials were submitted. The submission you witnessed establishes exposure in the simulation, but exposure alone does not prove later account use or explain the login.</p></section><section class="evidence-card"><b>NEED</b><h3>How to strengthen the claim</h3><p>Correlate endpoint or submission evidence, the employee’s account, identity-session details, MFA events and post-login activity before attributing cause or actor.</p></section><section class="evidence-card protection"><b>PROTECTION</b><h3>Verify before you trust</h3><ul><li>Verify the exact SSID with the venue. A matching name alone still does not guarantee authorization.</li><li>Consider data sensitivity before joining public Wi-Fi; use a trusted connection when appropriate.</li><li>A VPN encrypts traffic to the VPN operator. It does not make a fraudulent credential portal trustworthy.</li></ul></section></div><p class="reasoning-strip"><strong>PROVES → SUPPORTS → NEED</strong><br>State the fact. Qualify the inference. Identify the missing evidence.</p></article>'}
function reflectionView(){const s=RANGE_STEPS[rangeStep];if(rangeStep===6)return '<div id="frqReplay"></div>';
 if(rangeStep===2)return '<section class="reflection"><small>EMPLOYEE DECISION</small><h3>Your choice matters. The scenario remains a fixed teaching sequence.</h3><p>After recording your selection, follow the fictional employee who joins the near-match network. A safe choice here is acknowledged, not marked wrong.</p><div id="decisionFeedback" role="status" aria-live="polite" class="action-feedback"></div></section>';
 return '<section class="reflection"><small>EVIDENCE CHECKPOINT</small><h3>'+s.question+'</h3><div class="choice-list">'+s.choices.map(c=>'<button data-range-choice="'+c[0]+'" '+(rangeStep===3&&!portalSubmitted?'disabled':'')+'>'+esc(c[1])+'</button>').join('')+'</div><div id="decisionFeedback" role="status" aria-live="polite" class="action-feedback"></div></section>';
}
function renderRange(){
 const s=RANGE_STEPS[rangeStep];$('#mobileStep').textContent='STEP '+(rangeStep+1)+' OF 7 · '+s.perspective;$('#mobileTask').textContent=s.task;$('#stepLabel').textContent='STEP '+(rangeStep+1)+' OF 7';$('#missionPerspective').textContent=s.perspective;$('#missionTask').textContent=s.task;$('#missionLook').textContent=s.look;$('#missionDo').textContent=s.do;$('#missionAfter').textContent=s.after;$('#sceneTitle').textContent=s.title;$('#scenePerspective').textContent=s.perspective;$('#rangeBack').disabled=rangeStep===0;
 document.querySelectorAll('.journey li').forEach((el,i)=>{el.classList.toggle('active',i===rangeStep);el.classList.toggle('done',i<rangeStep);if(i===rangeStep)el.setAttribute('aria-current','step');else el.removeAttribute('aria-current')});
 $('#sceneContent').innerHTML=rangeStep===6?'':rangeStep===0||rangeStep===2?employeeView():rangeStep===1?attackerView():rangeStep===3?portalView():rangeStep===5?apView():socView();$('#checkpoint').innerHTML=reflectionView();renderSocEvents();updateRangeNavigation();
 if(rangeStep===2&&networkChoice)showNetworkFeedback();
 if(rangeStep===6){window.IRONCREST_FRQ.mount($('#frqReplay'),{packet:window.IRONCREST_FRQ.replayPacket(SOC_EVENTS),onStatus:done=>{replayComplete=done;$('#nextHint').textContent=done?'Written response recorded, not scored. Continue to Signal Lost below.':'Complete Parts A–D and the evidence self-check to record your response.'},onContinue:()=>{if(replayComplete)openBrief('U1-002')}});}
}
function chooseRange(answer){const s=RANGE_STEPS[rangeStep];if(!s.choices||rangeStep===3&&!portalSubmitted)return;const ok=answer===s.answer;if(ok)completedSteps.add(rangeStep);else completedSteps.delete(rangeStep);rangeFeedback(ok?s.feedback:'This claim goes beyond the evidence. Revisit the main view and try again.',ok);document.querySelectorAll('[data-range-choice]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.rangeChoice===answer)));updateRangeNavigation()}
function advanceRange(){if(rangeStep<6&&completedSteps.has(rangeStep)){rangeStep++;renderRange();$('#missionPerspective').focus({preventScroll:true});$('#sceneTitle').scrollIntoView({block:'start',behavior:'smooth'})}}
function resetRange(){rangeStep=0;portalSubmitted=false;networkChoice='';replayComplete=false;completedSteps.clear();renderRange()}
function showNetworkFeedback(){const messages={approved:'You selected the approved SSID, Bellweather-Guest. That matches the baseline. Next, observe the fictional employee taking the risky near-match path.',rogue:'You selected Bellweather_Guest, with an underscore. It is a near-match to the approved SSID. Stronger signal does not establish trust.',cafe:'You selected Cafe-Free-WiFi. It is not the approved network. Verify authorization and consider data sensitivity before joining.'};rangeFeedback(messages[networkChoice],networkChoice==='approved');document.querySelectorAll('[data-network]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.network===networkChoice)))}
function submitPortal(){if(rangeStep!==3||portalSubmitted)return;portalSubmitted=true;renderRange();rangeFeedback('Fictional form submission recorded locally. Now decide what this establishes in the checkpoint below.');$('#checkpoint').scrollIntoView({block:'nearest',behavior:'smooth'})}
function switchWorkspace(name){document.querySelectorAll(".workspace-tab").forEach(b=>b.classList.toggle("active",b.dataset.workspace===name));document.querySelectorAll(".workspace-panel").forEach(p=>p.classList.toggle("active",p.id==="workspace-"+name))}
function queue(){C=null;$("#console").classList.add("hidden");$("#briefing").classList.remove("hidden");$("#caseBrief").classList.add("hidden");$("#queueView").classList.remove("hidden");renderWorkspace()}
function openBrief(id){C=CASES[id];if(!C)return;loadState();$("#queueView").classList.add("hidden");$("#caseBrief").classList.remove("hidden");$("#briefId").textContent=C.id;$("#briefPriority").textContent="PRIORITY: "+C.priority;$("#briefTitle").textContent=C.title;$("#briefText").textContent=C.brief;$("#briefMission").textContent=C.mission;$("#briefResources").textContent=C.credits+" investigation credits. Additional evidence has a cost.";$("#briefStandard").textContent=C.standard;$("#roleSelect").innerHTML=C.roles.map(r=>'<option>'+esc(r)+'</option>').join("");$("#roleSelect").value=state.team||C.roles[0]}


$('#rangeReset').onclick=resetRange;
$('#rangeBack').onclick=()=>{if(rangeStep>0){rangeStep--;renderRange()}};
$('#rangeNext').onclick=advanceRange;
$('#queueView').addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b||b.disabled)return;
 if(b.dataset.rangeChoice)chooseRange(b.dataset.rangeChoice);
 if(b.dataset.network&&rangeStep===2){networkChoice=b.dataset.network;completedSteps.add(2);showNetworkFeedback();updateRangeNavigation();$('#checkpoint').scrollIntoView({block:'nearest',behavior:'smooth'})}
 if(b.id==='portalSubmit')submitPortal();
});
$('#queueView').addEventListener('input',e=>{if(e.target.id==='socSearch')renderSocEvents()});
$('#queueView').addEventListener('change',e=>{if(e.target.id==='socFilter')renderSocEvents()});

const intelContent={
 human:'<h2>IC-001 // Credential Harvesting Patterns</h2><p class="lead">Intelligence is context, not proof that a specific case matches a campaign.</p><div class="intel-brief"><b>OBSERVED PATTERNS</b><ul><li>Messages may combine authority or impersonation with urgency or threatened negative consequences.</li><li>Credential-harvesting pages imitate trusted services and request authentication information.</li><li>Credential exposure establishes that credentials were revealed; it does not by itself prove later account access.</li></ul><b>ANALYST QUESTIONS</b><ul><li>What exact language attempts to influence the target?</li><li>Did the user actually enter credentials?</li><li>What identity evidence exists after the exposure?</li></ul></div>',
 identity:'<h2>IC-002 // Suspicious Authentication Activity</h2><p class="lead">Correlate authentication events before deciding an account was compromised.</p><div class="intel-brief"><b>HIGH-VALUE OBSERVATIONS</b><ul><li>Many failed attempts in a short period.</li><li>Unusual sign-in time or unfamiliar device/source.</li><li>A success following failures.</li><li>MFA changes, new sessions, mailbox rules, or other post-login activity.</li></ul><b>CAUTION</b><p>A failed login is not successful access. An unfamiliar device is suspicious context, not automatic proof of malicious activity.</p></div>',
 wireless:'<h2>IC-003 // Public Network Threats</h2><p class="lead">Identify the mechanism from observable evidence.</p><div class="intel-brief"><b>EVIL TWIN</b><p>An adversary-operated access point imitates a legitimate SSID so users connect through it.</p><b>JAMMING</b><p>Radio-frequency interference prevents legitimate wireless communication and affects availability.</p><b>WAR DRIVING</b><p>Wireless reconnaissance gathers information about networks while moving through an area.</p><b>PROTECTION</b><p>Verify the exact SSID, consider data sensitivity before joining open Wi-Fi, and understand that a VPN protects traffic confidentiality but does not stop RF jamming.</p></div>'
};
document.querySelectorAll("[data-intel]").forEach(b=>b.onclick=()=>showModal(intelContent[b.dataset.intel]||"<p>No briefing available.</p>"));
const drillContent={
 psn:'<h2>DRILL 01 // Proves or Supports?</h2><p class="lead">An identity log shows 12 failed attempts from an unfamiliar source followed by one successful login. The user has not yet been interviewed.</p><p><b>Claim:</b> “The attacker stole the user’s password and used it to access the account.”</p><button class="drill-choice" data-answer="psn-proves">PROVES</button><button class="drill-choice" data-answer="psn-supports">SUPPORTS</button><button class="drill-choice" data-answer="psn-need">NEED MORE EVIDENCE</button><div id="drillFeedback" class="drill-feedback"></div>',
 auth:'<h2>DRILL 02 // Authentication Triage</h2><p class="lead">02:13 — four failed password attempts from an unknown browser. 02:14 — successful login from that browser. 02:17 — MFA settings changed.</p><p><b>Which observation most strongly strengthens the hypothesis of unauthorized post-login activity?</b></p><button class="drill-choice" data-answer="auth-fails">The failed attempts</button><button class="drill-choice" data-answer="auth-success">The successful login</button><button class="drill-choice" data-answer="auth-mfa">The MFA settings change</button><div id="drillFeedback" class="drill-feedback"></div>',
 wireless:'<h2>DRILL 03 // Name the Mechanism</h2><p class="lead">A venue advertises “HarborCenter-Guest.” A second access point named “HarborCenter_Guest” appears nearby and presents a sign-in portal.</p><p><b>Which mechanism is most directly supported?</b></p><button class="drill-choice" data-answer="wireless-evil">Evil twin</button><button class="drill-choice" data-answer="wireless-jam">Jamming</button><button class="drill-choice" data-answer="wireless-war">War driving</button><div id="drillFeedback" class="drill-feedback"></div>'
};
document.querySelectorAll("[data-drill]").forEach(b=>b.onclick=()=>showModal(drillContent[b.dataset.drill]));


document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{
 const tool=b.dataset.tool;
 if(tool==="psn")showModal('<h2>Proves / Supports / Need</h2><p class="lead">Use this before making an incident claim.</p><div class="tool-modal-grid"><div><b>PROVES</b>What can you state directly as fact from the evidence?</div><div><b>SUPPORTS</b>What conclusion does the evidence suggest but not independently prove?</div><div><b>NEED</b>What additional evidence would strengthen, challenge, or resolve the conclusion?</div></div><p><b>Analyst rule:</b> If your sentence goes beyond the observable evidence, move it from PROVES to SUPPORTS—or identify what you NEED.</p>');
 if(tool==="auth")showModal('<h2>Authentication Analyzer</h2><p class="lead">Triage suspicious identity activity with the same routine every time.</p><ol class="tool-checklist"><li>Look for many failed attempts in a short period.</li><li>Compare login time with the user\'s normal pattern.</li><li>Identify unfamiliar devices, source addresses, or locations.</li><li>Look for a success after failures.</li><li>Correlate MFA changes, new sessions, mailbox rules, or other post-login activity.</li><li>Separate credential exposure from evidence of actual account access.</li></ol><p><b>Finish with:</b> What does this PROVE, SUPPORT, and what do you still NEED?</p>');
 if(tool==="ioc")showModal('<h2>IOC Workbench</h2><p class="lead">Classify the observable before assigning meaning.</p><div class="tool-modal-grid"><div><b>IDENTIFIER</b>IP address, domain, URL, hash, username, hostname, email address.</div><div><b>CONTEXT</b>Where was it observed? When? In which data source? What action occurred?</div><div><b>ASSESSMENT</b>Benign, suspicious, malicious, or unknown must be supported by evidence.</div></div><p><b>Analyst rule:</b> An unfamiliar artifact is not automatically malicious. Record the context that makes it relevant.</p>');
});
$("#consoleToolkit").onclick=()=>showModal('<h2>Analyst Toolkit</h2><p class="lead">Use these routines while the case is open. They guide reasoning; they do not grade the case.</p><div class="tool-modal-grid"><div><b>PROVES</b>Directly established by the evidence.</div><div><b>SUPPORTS</b>Suggested by correlation or context, but not independently proven.</div><div><b>NEED</b>Evidence that would strengthen, challenge, or resolve the conclusion.</div></div><h3>Authentication triage</h3><ol class="tool-checklist"><li>Failed-attempt pattern</li><li>Unusual time</li><li>Unknown device / source</li><li>Success after failures</li><li>Post-login changes or activity</li></ol><h3>Observable / IOC routine</h3><p>Classify the artifact first → record where and when it appeared → decide whether the context makes it benign, suspicious, malicious, or still unknown.</p>');
$("#backQueue").onclick=queue;$("#caseQueue").onclick=queue;
$("#acceptCase").onclick=()=>{state.team=$("#roleSelect").value;save();$("#briefing").classList.add("hidden");$("#console").classList.remove("hidden");configure();render()};
function configure(){document.querySelector('[data-view="assessment"]').textContent=C.id==='U1-002'?'✎ FRQ Assessment':'✓ Incident Decision';$("#activeCaseId").textContent=C.id;$("#activeCaseTitle").textContent=C.title;$("#activePriority").textContent=C.priority;$("#telemetryNav").textContent=C.telemetryName;$("#telemetryKicker").textContent=C.telemetryKicker;$("#telemetryTitle").textContent=C.telemetryName;$("#objectiveText").textContent=C.objective;$("#objectiveSteps").innerHTML=C.objectiveSteps.map(x=>"<li>"+esc(x)+"</li>").join("");$("#drawerLabel").textContent=C.recordLabel;$("#search").placeholder="Search "+C.telemetryName.toLowerCase()+"…";$("#telemetryHeaders").innerHTML=C.columns.map(x=>"<th>"+esc(x.label)+"</th>").join("");$("#eventFilter").innerHTML='<option value="">All observation types</option>'+[...new Set(C.records.map(x=>x.event))].sort().map(x=>"<option>"+esc(x)+"</option>").join("");$("#resultFilter").innerHTML='<option value="">All statuses</option>'+[...new Set(C.records.map(x=>x.result))].sort().map(x=>"<option>"+esc(x)+"</option>").join("");buildCustomAssessment()}
function buildCustomAssessment(){const a=C.assessment||{fields:[]};$("#customAssessment").innerHTML=(a.fields||[]).map(f=>{const req=f.required?" required":"";if(f.type==="select")return '<label>'+esc(f.label)+'<select id="af_'+esc(f.id)+'"'+req+'><option value="">Select…</option>'+f.options.map(o=>"<option>"+esc(o)+"</option>").join("")+"</select></label>";if(f.type==="textarea")return '<label>'+esc(f.label)+'<textarea id="af_'+esc(f.id)+'" placeholder="'+esc(f.placeholder||"")+'"'+req+'></textarea></label>';return '<label>'+esc(f.label)+'<input id="af_'+esc(f.id)+'" placeholder="'+esc(f.placeholder||"")+'"'+req+'></label>'}).join("")}
$("#closeDrawer").onclick=()=>$("#drawer").classList.add("hidden");$("#closeModal").onclick=closeModal;
$("#resetCase").onclick=()=>showModal("<h2>Reset Case "+esc(C.id)+"?</h2><p>This clears this browser's case file, evidence requests, notes, and assessment for <b>"+esc(C.id)+"</b>. Other cases are not affected.</p><button type=\"button\" id=\"confirmReset\" class=\"danger modal-action\">RESET CASE</button>");
document.querySelectorAll("#console aside nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#console aside nav button,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.view).classList.add("active");if(b.dataset.view==="assessment")renderAssessment()});
function renderLogs(){const q=$("#search").value.toLowerCase(),ef=$("#eventFilter").value,rf=$("#resultFilter").value;const rows=C.records.filter(x=>(!q||Object.values(x).join(" ").toLowerCase().includes(q))&&(!ef||x.event===ef)&&(!rf||x.result===rf));$("#eventCount").textContent=rows.length+" records";$("#logRows").innerHTML=rows.map(x=>'<tr data-id="'+esc(x.id)+'">'+C.columns.map(col=>'<td class="'+(col.key==="result"?"result-"+String(x[col.key]).toLowerCase():"")+'">'+esc(x[col.key])+"</td>").join("")+"</tr>").join("")}
["search","eventFilter","resultFilter"].forEach(id=>$("#"+id).addEventListener(id==="search"?"input":"change",renderLogs));$("#clearFilters").onclick=()=>{$("#search").value="";$("#eventFilter").value="";$("#resultFilter").value="";renderLogs()};$("#logRows").onclick=e=>{const row=e.target.closest("tr[data-id]");if(row)openRecord(row.dataset.id)};
function openRecord(id){selected=C.records.find(x=>x.id===id);if(!selected)return;$("#drawerTitle").textContent=selected.id+" // "+selected.event;$("#drawerBody").innerHTML=Object.entries(selected).map(([k,v])=>'<div class="detailrow"><span>'+esc(k.toUpperCase())+'</span><span>'+esc(v)+"</span></div>").join("");$("#drawer").classList.remove("hidden")}
$("#pinEvent").onclick=()=>{if(!selected)return;showModal("<h2>Add "+esc(selected.id)+" to Case</h2><p><b>Why does this record matter?</b></p><p class=\"lead\">Explain what you noticed or how it relates to your current hypothesis.</p><textarea id=\"eventReason\" rows=\"4\" placeholder=\"Analyst observation…\" required></textarea><button type=\"button\" id=\"confirmPin\" class=\"primary modal-action\" disabled>ADD TO CASE FILE</button>")};
function renderEvidence(){const total=C.credits||3;$("#creditDots").textContent=Array(state.credits).fill("●").join(" ")+" "+Array(total-state.credits).fill("○").join(" ");$("#evidenceCards").innerHTML=C.evidence.map(ev=>{const u=state.unlocked.includes(ev.id);return '<article class="ecard '+(u?"unlocked":"")+'"><small>'+(u?"UNLOCKED":"AVAILABLE // 1 CREDIT")+"</small><h3>"+esc(ev.title)+"</h3><p>"+esc(ev.desc)+'</p><button data-e="'+esc(ev.id)+'">'+(u?"VIEW EVIDENCE":"REQUEST EVIDENCE")+"</button></article>"}).join("")}
$("#evidenceCards").onclick=e=>{const b=e.target.closest("[data-e]");if(b)requestEvidence(b.dataset.e)};
function requestEvidence(id){const ev=C.evidence.find(x=>x.id===id);if(!ev)return;pendingEvidence=ev;if(state.unlocked.includes(id))return showEvidence(ev);if(state.credits<=0)return showModal("<h2>No credits remaining</h2><p>Work with the evidence your team has already collected.</p>");showModal("<h2>Evidence Request: "+esc(ev.title)+"</h2><p>What investigative question are you trying to answer, and why would this source help?</p><textarea id=\"evidenceQuestion\" rows=\"4\" placeholder=\"Enter your investigative question…\" required></textarea><button type=\"button\" id=\"confirmSpend\" class=\"primary modal-action\" disabled>SPEND 1 CREDIT & REVEAL</button>")}
function showEvidence(ev){pendingEvidence=ev;const added=state.evidenceAdded.includes(ev.id);showModal(ev.content+'<div class="evidence-question"><small>YOUR INVESTIGATIVE QUESTION</small><p>'+esc(state.evidenceQuestions[ev.id]||"Previously unlocked evidence")+'</p></div><button id="addEvidence" class="primary modal-action" '+(added?"disabled":"")+">"+(added?"ADDED TO CASE":"ADD TO CASE")+"</button>")}
$("#timelineForm").onsubmit=e=>{e.preventDefault();const t=$("#timelineText").value.trim();if(!t)return;state.timeline.push({type:"note",time:$("#timelineTime").value||"—",title:"Analyst Observation",source:"Manual entry",observation:t});$("#timelineTime").value=$("#timelineText").value="";save();renderTimeline()};
function sortTimeline(items){return items.map((x,i)=>({...x,_i:i})).sort((a,b)=>{const ta=/^\d\d:\d\d/.test(a.time)?a.time:"99:99:99",tb=/^\d\d:\d\d/.test(b.time)?b.time:"99:99:99";return ta.localeCompare(tb)})}
function renderTimeline(){const items=sortTimeline(state.timeline);$("#timelineList").innerHTML=items.length?items.map(x=>'<div class="entry '+esc(x.type||"legacy")+'"><div class="entrytop"><span class="badge">'+esc(String(x.type||"legacy").toUpperCase())+"</span><b>"+esc(x.time||"—")+'</b><button type="button" data-del="'+x._i+'" title="Remove finding">×</button></div><h3>'+esc(x.title||"Finding")+'</h3><div class="entrysource">'+esc(x.source||"")+"</div><p><strong>Analyst observation:</strong> "+esc(x.observation||x.text||"")+"</p></div>").join(""):'<p class="hint">No findings in the case file yet.</p>';renderAssessment()}
$("#timelineList").onclick=e=>{const b=e.target.closest("[data-del]");if(!b)return;const i=Number(b.dataset.del);if(Number.isInteger(i)&&i>=0&&i<state.timeline.length){state.timeline.splice(i,1);save();renderTimeline()}};
$("#caseNotes").oninput=e=>{state.notes=e.target.value;save();$("#saveFlag").textContent="Saved.";renderAssessment()};
function customValues(){const vals={};(C.assessment.fields||[]).forEach(f=>{const el=$("#af_"+f.id);vals[f.id]=el?el.value.trim():""});return vals}
function populateAssessment(){const a=state.assessment||{};$("#disposition").value=a.disposition||"";$("#happened").value=a.happened||"";$("#proves").value=a.proves||"";$("#supports").value=a.supports||"";$("#need").value=a.need||"";$("#nextAction").value=a.nextAction||"";(C.assessment.fields||[]).forEach(f=>{const el=$("#af_"+f.id);if(el)el.value=(a.custom||{})[f.id]||""})}
function customReportHtml(a){const labels=C.assessment.reportLabels||{};return Object.entries(a.custom||{}).map(([k,v])=>'<div><small>'+esc(labels[k]||k.toUpperCase())+"</small><p>"+esc(v)+"</p></div>").join("")}
function reportText(){const a=state.assessment||{},labels=C.assessment.reportLabels||{};const custom=Object.entries(a.custom||{}).map(([k,v])=>"\n"+(labels[k]||k.toUpperCase())+"\n"+v).join("");const findings=sortTimeline(state.timeline).map(x=>"- "+(x.time||"—")+" | "+(x.title||"Finding")+": "+(x.observation||x.text||"")).join("\n");return "IRONCREST CYBER PARTNERS — SOC BRIEFING\nCase: "+C.id+" — "+C.title+"\nAnalyst Team: "+(state.team||"Unassigned")+"\n\nDISPOSITION\n"+(a.disposition||"")+custom+"\n\nINCIDENT ASSESSMENT\n"+(a.happened||"")+"\n\nPROVES\n"+(a.proves||"")+"\n\nSUPPORTS\n"+(a.supports||"")+"\n\nNEED\n"+(a.need||"")+"\n\nRECOMMENDED NEXT ACTION\n"+(a.nextAction||"")+"\n\nCASE FILE FINDINGS\n"+(findings||"No findings recorded.")}
function renderReport(){const a=state.assessment;if(!a)return;$("#reportDisposition").textContent=a.disposition;$("#reportBody").innerHTML='<div class="report-grid">'+customReportHtml(a)+'<div><small>ANALYST TEAM</small><p>'+esc(state.team)+'</p></div></div><section><small>INCIDENT ASSESSMENT</small><p>'+esc(a.happened)+'</p></section><div class="triple report-reasoning"><section><small>PROVES</small><p>'+esc(a.proves)+'</p></section><section><small>SUPPORTS</small><p>'+esc(a.supports)+'</p></section><section><small>NEED</small><p>'+esc(a.need)+'</p></section></div><section><small>RECOMMENDED NEXT ACTION</small><p>'+esc(a.nextAction)+'</p></section><section><small>CASE FILE FINDINGS</small>'+sortTimeline(state.timeline).map(x=>'<div class="report-finding"><b>'+esc(x.time)+" · "+esc(x.title)+"</b><span>"+esc(x.observation||x.text||"")+"</span></div>").join("")+"</section>"}
function renderAssessment(){if(!C||!state)return;
 if(C.id==='U1-002'){
  $('#assessment').classList.add('frq-mode');
  let host=$('#frqCaseAssessment');if(!host){host=document.createElement('div');host.id='frqCaseAssessment';$('#assessment').appendChild(host)}
  window.IRONCREST_FRQ.mount(host,{packet:window.IRONCREST_FRQ.casePacket(C,state),legacy:state.assessment?reportText():''});return;
 }
 $('#assessment').classList.remove('frq-mode');if($('#frqCaseAssessment'))$('#frqCaseAssessment').remove();
$("#statusTimeline").textContent=state.timeline.length;$("#statusEvidence").textContent=state.unlocked.length+" / "+(C.credits||3);$("#statusNotes").textContent=state.notes.trim()?"SAVED":"NONE";$("#assessmentFindings").innerHTML=state.timeline.length?'<small>CASE FILE FINDINGS</small>'+sortTimeline(state.timeline).map(x=>'<div class="mini-finding"><b>'+esc(x.time)+" · "+esc(x.title)+"</b><span>"+esc(x.observation||x.text||"")+"</span></div>").join(""):'<p class="hint">Your case file has no findings yet. Return to the investigation before making a disposition.</p>';const done=!!state.assessment&&!editingAssessment;$("#assessmentForm").classList.toggle("hidden",done);$("#submitted").classList.toggle("hidden",!done);if(done)renderReport();else populateAssessment()}
$("#assessmentForm").onsubmit=e=>{e.preventDefault();state.assessment={disposition:$("#disposition").value,custom:customValues(),happened:$("#happened").value.trim(),proves:$("#proves").value.trim(),supports:$("#supports").value.trim(),need:$("#need").value.trim(),nextAction:$("#nextAction").value.trim()};editingAssessment=false;save();renderAssessment()};
$("#editAssessment").onclick=()=>{editingAssessment=true;renderAssessment();$("#assessmentForm").scrollIntoView({behavior:"smooth",block:"start"})};
$("#copyBriefing").onclick=async()=>{const t=reportText(),s=$("#copyStatus");try{await navigator.clipboard.writeText(t)}catch(e){const ta=document.createElement("textarea");ta.value=t;document.body.appendChild(ta);ta.select();document.execCommand("copy");ta.remove()}s.textContent="Copied — paste into Schoology.";setTimeout(()=>s.textContent="",3500)};
document.addEventListener("input",e=>{const id=e.target&&e.target.id;if(id==="eventReason"&&$("#confirmPin"))$("#confirmPin").disabled=!e.target.value.trim();if(id==="evidenceQuestion"&&$("#confirmSpend"))$("#confirmSpend").disabled=!e.target.value.trim();if(id==="evidenceReason"&&$("#confirmEvidence"))$("#confirmEvidence").disabled=!e.target.value.trim()},true);
document.addEventListener("click",e=>{const b=e.target.closest&&e.target.closest("button");if(!b)return;
if(b.classList.contains("drill-choice")){
 const f=$("#drillFeedback"),a=b.dataset.answer;
 const messages={
 "psn-proves":"Not yet. The log proves the failures and success occurred, but not how the credential was obtained or who used it.",
 "psn-supports":"The sequence supports suspicious or possibly unauthorized access, but the full claim goes beyond the evidence.",
 "psn-need":"Correct. You need additional evidence before claiming password theft and attacker use. Separate the observed login sequence from the cause.",
 "auth-fails":"Useful indicator, but failed attempts do not establish post-login activity.",
 "auth-success":"Stronger, but the question asks specifically for evidence of activity after access.",
 "auth-mfa":"Correct. The MFA change is post-login account activity and materially strengthens the unauthorized-access hypothesis.",
 "wireless-evil":"Correct. The near-match SSID plus sign-in portal directly supports an evil-twin / impersonating access-point hypothesis.",
 "wireless-jam":"Not from these observations. Jamming requires evidence of RF interference or availability disruption.",
 "wireless-war":"Not from these observations. War driving is reconnaissance; a nearby rogue SSID does not prove how it was discovered or deployed."
 };f.textContent=messages[a]||"";f.classList.add("show");return;
}
if(b.id==="confirmPin"){const t=$("#eventReason");if(!t||!t.value.trim()||!selected)return;state.timeline.push({type:"log",time:selected.time,title:selected.id+" — "+selected.event,source:C.columns.slice(1,3).map(x=>selected[x.key]).join(" · ")+" · "+selected.resource,observation:t.value.trim()});save();renderTimeline();closeModal();$("#drawer").classList.add("hidden")}else if(b.id==="confirmSpend"){const t=$("#evidenceQuestion");if(!t||!t.value.trim()||!pendingEvidence||state.credits<=0)return;if(!state.unlocked.includes(pendingEvidence.id)){state.credits--;state.unlocked.push(pendingEvidence.id)}state.evidenceQuestions[pendingEvidence.id]=t.value.trim();save();renderEvidence();showEvidence(pendingEvidence)}else if(b.id==="addEvidence"){if(b.disabled||!pendingEvidence)return;showModal(pendingEvidence.content+'<h3>Why does this evidence matter?</h3><p class="lead">Explain what it proves or supports in your investigation.</p><textarea id="evidenceReason" rows="4" placeholder="Analyst interpretation…"></textarea><button type="button" id="confirmEvidence" class="primary modal-action" disabled>ADD TO CASE FILE</button>')}else if(b.id==="confirmEvidence"){const t=$("#evidenceReason");if(!t||!t.value.trim()||!pendingEvidence)return;if(!state.evidenceAdded.includes(pendingEvidence.id)){state.evidenceAdded.push(pendingEvidence.id);state.timeline.push({type:"evidence",time:"EVIDENCE",title:pendingEvidence.title,source:"Evidence Locker",observation:t.value.trim()})}save();renderEvidence();renderTimeline();closeModal()}else if(b.id==="confirmReset"){const resetId=C.id;localStorage.removeItem(KEY);if(resetId==="U1-002")localStorage.removeItem("ironcrest-frq-signal-lost-v1");closeModal();openBrief(resetId)}},true);
function render(){$("#teamName").textContent=state.team;$("#caseNotes").value=state.notes;renderLogs();renderEvidence();renderTimeline();renderAssessment()}
queue()})();
