/* Real-world context precedes the fictional experience. Sources checked 2026-09-27. */
(() => {
 'use strict';
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const data={
  'U1-001':{topic:'1.2 · Suspicious Website Logins',headline:'One compromised account can lead to more access.',source:'Microsoft Security Response Center',date:'January 19, 2024',title:'Microsoft Actions Following Attack by Nation State Actor Midnight Blizzard',url:'https://www.microsoft.com/en-us/msrc/blog/2024/01/microsoft-actions-following-attack-by-nation-state-actor-midnight-blizzard',kind:'Incident report',summary:'Microsoft reported that password spraying compromised a legacy test account. The attackers then used its permissions to reach some corporate mailboxes and take emails and attachments.',connection:'In Possible Account Compromise, you will compare sign-in activity with what happens after authentication. A successful login is an event to investigate, not proof that the account owner approved it.',question:'After an unfamiliar successful login, which account changes or data-access events would you inspect next?',focus:'Follow access beyond the initial login.',boundary:'This is a dated account of Microsoft’s investigation, not a reconstruction of its full incident or evidence about jsmith.'},
  'U1-002':{topic:'1.3 · Best Practices for Public Networks',headline:'A familiar Wi-Fi name can hide an unfamiliar operator.',source:'Australian Federal Police release, republished by The National Tribune',date:'June 28, 2024',title:'Man charged over creation of ‘evil twin’ free WiFi networks to access personal data',url:'https://www.nationaltribune.com.au/man-charged-over-creation-of-evil-twin-free-wifi-networks-to-access-personal-data/',kind:'Historical investigation report',summary:'In this 2024 release, Australian police alleged that fake public Wi-Fi networks directed people to pages requesting email or social-media logins. Investigators reported finding other people’s credentials and fraudulent Wi-Fi pages on seized devices.',connection:'In Signal Lost, compare the approved network with a look-alike and examine what a sign-in portal requests. Later, separate what you saw as a student from what the defender’s records actually show.',question:'What would establish that a network is authorized—and what additional evidence would show that someone submitted credentials?',focus:'Distinguish a familiar name from verified authorization.',boundary:'The linked release reports allegations at the time of charging; it is not a statement of the current legal outcome. The Bellweather case is fictional.'},
  'U1-003':{topic:'1.1 · Understanding Social Engineering',headline:'Attackers can target the people who control access.',source:'FBI, CISA, and international partner agencies',date:'July 29, 2025 update',title:'Scattered Spider · Joint Cybersecurity Advisory AA23-320A',url:'https://www.ic3.gov/CSA/2025/250729.pdf',kind:'Threat advisory · PDF',summary:'The joint advisory describes attackers impersonating employees or support personnel to manipulate help desks and obtain access. It documents social-engineering methods that can undermine password and MFA protections.',connection:'In Chain Reaction, examine how a message pressures an employee to act. Then investigate the message, network, and account records without assuming that events close together must share one cause.',question:'How could a help desk or employee verify an urgent request without relying on the requester’s own contact details?',focus:'Identify the influence tactic and the verification step it tries to bypass.',boundary:'This advisory illustrates social engineering. It does not establish a wireless attack or identify the actor in the fictional Chain Reaction case.'},
  'U1-004':{topic:'1.4 · AI-Based Cybersecurity Attacks',headline:'A convincing voice is not identity verification.',source:'FBI Internet Crime Complaint Center',date:'May 15, 2025',title:'Senior US Officials Impersonated in Malicious Messaging Campaign',url:'https://www.ic3.gov/PSA/2025/PSA250515',kind:'Public threat warning',summary:'The FBI warned of a campaign using texts and AI-generated voice messages to impersonate senior officials. Attackers tried to build trust and direct targets to links that could help them gain access to personal accounts.',connection:'In Borrowed Voice, a familiar-sounding caller asks for customer information. You will practice independent verification and examine a second risk: copying confidential details into a personal AI chatbot while asking for advice.',question:'If the voice sounds familiar, what independent check would you make before sharing sensitive information?',focus:'Verify the request through a trusted route.',boundary:'The FBI warning supports the voice-impersonation connection. The chatbot disclosure is a separate fictional teaching example, not an event reported in this advisory.'},
  'U1-005':{topic:'1.5 · Leveraging AI in Cyber Defense',headline:'Machine learning can help defenders interrupt an attack.',source:'Microsoft Defender Security Research Team',date:'October 8, 2019',title:'In hot pursuit of elusive threats: AI-driven behavior-based blocking stops attacks in their tracks',url:'https://www.microsoft.com/en-us/security/blog/2019/10/08/in-hot-pursuit-of-elusive-threats-ai-driven-behavior-based-blocking-stops-attacks-in-their-tracks/',kind:'Historical defensive case study',summary:'Microsoft described a credential-theft campaign targeting 100 organizations and reported that behavior-based machine learning detected and blocked attack stages. The report explains how behavior sequences supplied signals for classification and response.',connection:'In Signal or Noise, you will evaluate an AI-ranked queue against original records and approved activity. You will also review suggested security changes before deciding what to apply.',question:'What evidence and testing would you require before letting an AI alert trigger a disruptive action?',focus:'Connect the model’s inputs, its decision, and the response.',boundary:'This vendor report describes a defensive success. The false alerts and missed events in Signal or Noise are fictional practice, not claims about that reported deployment.'}
 };
 function show(host,id,proceed,home,direct=false){
  const d=data[id],name=window.IRONCREST_UNIT1.catalog.find(x=>x.id===id).name;
  host.innerHTML=`<section class="intel-opening"><button class="unit-secondary" data-intel-home>← All exercises</button><p class="unit-eyebrow">START HERE · REAL-WORLD THREAT BRIEFING · ${esc(id)}</p><h1>${esc(name)}</h1><p class="intel-topic">AP Cybersecurity · ${esc(d.topic)}</p><p class="intel-task"><strong>Your task:</strong> Read the short briefing, consider the guiding question, then enter the fictional activity. Open the source for the full report.</p><article class="intel-report"><span class="intel-type">${esc(d.kind)}</span><h2>${esc(d.headline)}</h2><p class="intel-byline">${esc(d.source)} · ${esc(d.date)}</p><h3>What happened?</h3><p>${esc(d.summary)}</p><a class="intel-source" href="${esc(d.url)}" target="_blank" rel="noopener noreferrer">Read source: ${esc(d.title)} ↗</a><p class="intel-source-note">Opens in a new tab. This summary is written for the activity; it is not a quotation.</p></article><section class="intel-connection"><h2>Why this matters for your mission</h2><p>${esc(d.connection)}</p><p><strong>Keep in mind:</strong> ${esc(d.focus)}</p></section><section class="intel-question"><h2>Before you begin</h2><p>${esc(d.question)}</p><p class="intel-source-note">Think about your answer or discuss it with your team. Revisit it after the investigation.</p></section><details class="intel-boundary"><summary>How this source relates to the fictional case</summary><p>${esc(d.boundary)}</p><p>Use the case’s own records in your Final FRQ. This briefing supplies context, not case evidence.</p></details><p class="intel-path">Real-world briefing → Guided experience → Defender investigation → Final FRQ</p><button data-intel-begin>${direct?'Continue to case briefing':'Begin guided experience'} →</button></section>`;
  host.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-intel-home'))home();else if(b.hasAttribute('data-intel-begin'))proceed()};
  window.scrollTo(0,0);
 }
 window.IRONCREST_INTEL={data,show};
})();
