/* Concrete rehearsal screens; the following investigation retains its own evidence. */
(() => {
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const stories={
  'U1-001':{employee:'Maya Chen',org:'Client IT',account:'mchen',device:'TRAIN-LT-08',signin:'login.client.example',fake:'account-review.example',intro:'You are helping Maya Chen check an unexpected account message. First, learn her normal sign-in routine. Watch what changes, then investigate a separate alert for jsmith in the case workspace.',goal:'Compare expected sign-ins with unfamiliar activity, then explain what the records do and do not establish.'},
  'U1-003':{employee:'Morgan Lee',org:'Northstar Health Services',account:'mlee',device:'TRAIN-LT-24',signin:'login.northstar.example',fake:'northstar-benefits.example',wifi:'HarborCenter-Guest',rogue:'HarborCenter_Guest',intro:'You are helping Morgan Lee prepare for a conference. First, check the company sign-in instructions and venue Wi-Fi notice. Then follow an unexpected message and network connection. After practice, investigate dlee’s separate Chain Reaction case.',goal:'Recognize deceptive requests and compare several sources without assuming that one event caused another.'}
 };
 const lessons=window.IRONCREST_UNIT1.lessons;
 for(const [id,d] of Object.entries(stories)){
  const chain=id==='U1-003',s=lessons[id];
  Object.assign(s[0],{title:chain?'Check the two approved details before the trip.':'Learn Maya’s normal sign-in routine.',task:chain?'Read the IT notice and venue notice. Identify the approved website and Wi-Fi name.':'Read Maya’s IT profile. Identify her expected device and sign-in protection.',look:chain?'The exact website address and Wi-Fi name shown on the two notices.':'The managed laptop name and the MFA requirement.',action:chain?'Select the answer that matches both notices.':'Select the device and sign-in method shown in the profile.',question:chain?'Which website and network match the notices?':'Which sign-in matches Maya’s IT profile?',choices:chain?[d.fake+' + '+d.rogue,d.signin+' + '+d.wifi,d.signin+' + '+d.rogue]:[d.device+' with a password and approved MFA factor','Any laptop with a password only','Any device displaying the company logo'],answer:chain?1:0,feedback:chain?'Correct. Keep login.northstar.example and HarborCenter-Guest in mind. Next, you will see a message that uses a different address.':'Correct. The managed laptop and MFA provide the expected comparison. An unfamiliar device later deserves investigation.',heading:'Approved information'});
  Object.assign(s[1],{title:'See what the adversary wants the employee to do.',task:chain?'Read the lure and identify the pressure tactic.':'Read the adversary’s objective and distinguish intent from evidence.',look:chain?'The deadline and threatened payroll problem.':'The desired account access; the defender has not observed this plan.',action:chain?'Choose the tactic demonstrated by the wording.':'Choose what the defender would need before making a claim.'});
  Object.assign(s[2],{title:'Compare this email with the approved information.',task:'Inspect the sender, destination, and requested action before responding.',look:'Compare the message destination with '+d.signin+'.',action:'Choose how the employee should verify the request.',feedback:'Correct. Verify through the known company route. The next screen demonstrates the risky choice so you can see what credential exposure means.'});
  Object.assign(s[3],{title:chain?'Watch the two fictional submissions.':'Watch a fictional credential submission.',task:'Show the simulated outcome, then decide what it establishes.',look:'An explicit submission is different from a page visit or a later login.',action:'Select Show simulated outcome, then answer the question.',question:chain?'Do two submissions tell us which one caused a later login?':'What does the submission event establish?',feedback:chain?'No. Two exposure opportunities do not identify the cause of the later session. The SOC must investigate each possible connection.':'The credentials were exposed in this practice scenario. Later account use still requires separate evidence.'});
  Object.assign(s[4],{title:'Now you are the defender. What can you support?',task:'Read the security events shown below and choose the supported conclusion.',look:'The recorded action in each row. The defender cannot see the submission receipts.',action:'Use only these rows to answer the question.'});
  Object.assign(s[6],{title:'Practice finished. Accept your case assignment.',task:chain?'Investigate dlee’s Chain Reaction alert using the case evidence.':'Investigate jsmith’s account alert using the case evidence.',look:'The case briefing introduces a different employee and a new set of records.',action:'Open the briefing, accept your team assignment, and inspect the records.'});
 }
 function frame(title,body,kind=''){return `<div class="story-window ${kind}"><div class="story-bar"><strong>${esc(title)}</strong><span aria-hidden="true">− □ ×</span></div>${body}</div>`}
 function render(id,index,exposed){const d=stories[id],chain=id==='U1-003';
  if(index===0)return frame(chain?'Travel preparation · trusted notices':'Employee profile · Client IT',`<div class="story-notices"><article><span class="story-tag">FROM YOUR IT DEPARTMENT</span><h3>${chain?'Company sign-in':'Maya Chen · approved profile'}</h3><p>${chain?'Use this address to access your work account:':'Use the assigned company laptop:'}</p><code>${esc(chain?d.signin:d.device)}</code><p>${chain?'Open your saved company bookmark or type this address yourself.':'Sign in with your password and approved MFA factor. A password alone is not the complete sign-in procedure.'}</p></article><article><span class="story-tag">${chain?'FROM CONFERENCE STAFF':'EXPECTED ACTIVITY'}</span><h3>${chain?'Guest Wi-Fi':'Workday sign-in'}</h3>${chain?`<p>The venue’s approved guest network is:</p><code>${d.wifi}</code><p>Compare every character. Ask venue staff if the available names do not match.</p>`:'<p>09:00 · Managed laptop sign-in</p><p>09:02 · MFA verification completed</p><p>Use this routine to compare the activity you see later.</p>'}</article></div>`);
  if(index===1)return frame('Scenario director · adversary perspective',`<div class="story-director"><span class="story-tag">YOU CAN SEE THE PLAN · THE SOC CANNOT</span><h3>${chain?'Pressure the employee into acting quickly':'Obtain access to the employee’s mailbox'}</h3><blockquote>${chain?'“Verify immediately or your payroll access may be delayed.”':'“Make this look like a routine account review so the employee enters work credentials.”'}</blockquote><p>This shows the adversary’s intent for the demonstration. It is not evidence available in the later case.</p></div>`,'story-dark');
  if(index===2)return frame('Mail · '+d.employee,`<div class="story-mail"><div class="story-mailnav">Inbox <span>1 unread</span></div><article><h3>${chain?'Payroll verification required':'Work account review requested'}</h3><dl><dt>From</dt><dd>${chain?'Benefits Desk':'Account Services'} &lt;review@${d.fake}&gt;</dd><dt>To</dt><dd>${d.employee}</dd></dl><p>${chain?'Verify before 08:30 to avoid a delay in payroll access.':'Review your work account today to maintain access.'}</p><p>Enter your work email and password at:</p><code>${d.fake}/verify</code><p class="story-compare">Your IT notice listed <strong>${d.signin}</strong>. Does this destination match?</p><small>Fictional message. The displayed address is not a live link.</small></article></div>`);
  if(index===3)return frame('Browser demonstration · '+d.employee,`<div class="story-browser"><div class="story-address">${d.fake}/verify</div><div class="story-form"><h3>Verify your work account</h3><label>Training account<input readonly value="${d.account}@training.example" aria-label="Fictional training account"></label><label>Training password<input readonly value="Fictional example only" aria-label="Fictional training password"></label>${!exposed?'<button data-story-submit>Show simulated outcome →</button>':`<div role="status" class="story-receipt"><strong>Simulated submission recorded</strong><p>The employee sends the fictional credentials to the imitation page.</p>${chain?'<p>A few minutes later, the employee joins HarborCenter_Guest and submits the same credentials to its portal. The approved notice said HarborCenter-Guest.</p>':''}<p>This confirms exposure in the demonstration. It does not identify who later used the account.</p></div>`}<small>This demonstration sends nothing and accepts no personal credentials.</small></div></div>`);
  if(index===4){const rows=chain?[['10:04','Web gateway','Visit to '+d.fake],['10:08','Endpoint','Association with '+d.rogue],['10:09','Web sensor','Portal observed; no form-submission record'],['10:14','Identity / mail','Unfamiliar session creates a mailbox rule']]:[['09:10:02','Identity','Failed login · unfamiliar browser · mchen'],['09:10:21','Identity','Successful login · unfamiliar browser · mchen'],['09:11:07','Identity','New MFA method registered in the same session']];return frame('Security operations · event timeline',`<div class="story-soc"><p class="story-alert">Investigate · unfamiliar account activity</p>${rows.map(r=>`<div class="story-event"><time>${r[0]}</time><b>${r[1]}</b><span>${esc(r[2])}</span></div>`).join('')}<p class="story-compare"><strong>Visibility limit:</strong> These events do not include the employee’s submission receipts. Do not use your earlier view as defender evidence.</p></div>`)}
  return frame('Assignment handoff',`<div class="story-form"><h3>${chain?'Chain Reaction · dlee':'Possible Account Compromise · jsmith'}</h3><p>You have practiced with ${d.employee}. Now apply the same reasoning to a different employee’s alert.</p><ol><li>Accept the case and inspect its records.</li><li>Request evidence to test your questions.</li><li>Record findings, then submit the Final FRQ.</li></ol><p>Use only the sources inside the case workspace in your final response.</p></div>`);
 }
 const coverage=`<section class="unit-how" aria-label="Unit 1 coverage"><h2>Unit 1 coverage · still in development</h2><p>These three exercises address Topics 1.1–1.3. They are not a complete Unit 1 collection or a claim that every objective is covered.</p><ul><li><strong>1.1 · Social engineering:</strong> Chain Reaction</li><li><strong>1.2 · Suspicious website logins:</strong> Possible Account Compromise and Chain Reaction</li><li><strong>1.3 · Public networks:</strong> Signal Lost and Chain Reaction</li><li><strong>1.4 · AI-Based Cybersecurity Attacks:</strong> No activity yet</li><li><strong>1.5 · Leveraging AI in Cyber Defense:</strong> No activity yet</li></ul><a href="https://apcentral.collegeboard.org/media/pdf/ap-cybersecurity-course-and-exam-description.pdf#page=38" target="_blank" rel="noopener noreferrer">College Board Unit 1 framework ↗</a></section>`;
 window.IRONCREST_STORY={stories,render,coverage};
})();
