(()=>{const CASES=window.IRONCREST_CASES,$=s=>document.querySelector(s);let C=null,state=null,KEY="",selected=null,pendingEvidence=null,editingAssessment=false;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const showModal=html=>{$("#modalBody").innerHTML=html;$("#modal").classList.remove("hidden")},closeModal=()=>$("#modal").classList.add("hidden");
function defaults(c){return{credits:c.credits||3,unlocked:[],timeline:[],notes:"",evidenceQuestions:{},evidenceAdded:[],team:c.roles[0],assessment:null}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function loadState(){KEY="ironcrest-"+C.id.toLowerCase();state=Object.assign(defaults(C),JSON.parse(localStorage.getItem(KEY)||"{}"));state.timeline=(state.timeline||[]).map(x=>x&&x.type?x:{type:"legacy",time:(x&&x.time)||"—",title:"Migrated Finding",source:"Legacy case file",observation:(x&&x.text)||"Imported finding."});save()}
function caseState(c){try{return JSON.parse(localStorage.getItem("ironcrest-"+c.id.toLowerCase())||"{}")}catch(e){return{}}}

const ALERT_KEY="ironcrest-alert-correlation-v1";
const ALERTS=[
 {id:"ALT-260926-071",time:"07:54",sev:"MED",source:"EMAIL",client:"Northstar Health Services",title:"Employee-reported benefits message",summary:"External message uses a payroll deadline and directs the user to a benefits verification site.",detail:"Display name: Northstar Benefits. Subject: Payroll verification required before 08:30. Message contains a link to northstar-benefits.example/verify.",caseId:"U1-003"},
 {id:"ALT-260926-084",time:"08:03",sev:"LOW",source:"WEB",client:"Northstar Health Services",title:"Unusual external sign-in page",summary:"Managed laptop visited an external benefits domain that presented a corporate-style sign-in form.",detail:"Web gateway observed NHS-LT-24 visit northstar-benefits.example/verify. The gateway can see the page request, but cannot establish what the user typed.",caseId:"U1-003"},
 {id:"ALT-260926-096",time:"08:08",sev:"MED",source:"WIRELESS",client:"Northstar Health Services",title:"Near-match guest SSID detected",summary:"A wireless network similar to the approved conference guest network appeared in the same area.",detail:"Approved SSID: HarborCenter-Guest. Observed near-match: HarborCenter_Guest. Sensor also observed BSSID D2:44:9A:18:71:02; its authorization status is not established by this alert alone.",caseId:"U1-003"},
 {id:"ALT-260926-111",time:"08:13",sev:"HIGH",source:"IDENTITY",client:"Northstar Health Services",title:"Failures followed by successful sign-in",summary:"Three password failures from an unfamiliar source were followed by a successful sign-in for the same account.",detail:"Account dlee: 3 failures from 198.51.100.62 between 08:12:46 and 08:13:11, followed by LOGIN_SUCCESS at 08:13:29 from an unknown browser.",caseId:"U1-003"},
 {id:"ALT-260926-123",time:"08:15",sev:"HIGH",source:"MAIL",client:"Northstar Health Services",title:"New security-message inbox rule",summary:"A new rule was created during the unfamiliar cloud session.",detail:"Mail service recorded a rule for dlee that moves messages containing 'security' to Archive. This is post-login activity; determine whether the user authorized it.",caseId:"U1-003"}
];
function alertState(){try{return Object.assign({working:[],held:[],incidentCreated:false,opened:[]},JSON.parse(localStorage.getItem(ALERT_KEY)||"{}"))}catch(e){return{working:[],held:[],incidentCreated:false,opened:[]}}}
function saveAlertState(s){localStorage.setItem(ALERT_KEY,JSON.stringify(s))}
function renderWorkspace(){
 const s=alertState(),working=new Set(s.working||[]),held=new Set(s.held||[]),opened=new Set(s.opened||[]);
 const active=s.incidentCreated?1:0;
 $("#statAlerts").textContent=ALERTS.filter(a=>!working.has(a.id)&&!held.has(a.id)).length;
 $("#statWorking").textContent=working.size;
 $("#statCases").textContent=active;
 $("#workingCount").textContent="("+working.size+")";
 $("#createIncident").disabled=working.size<2||s.incidentCreated;
 $("#createIncident").textContent=s.incidentCreated?"INCIDENT CREATED":"CREATE INCIDENT ("+working.size+")";
 $("#incidentHint").textContent=s.incidentCreated?"U1-003 created from correlated observations. Open the incident to investigate.":"Build a defensible working set before escalating.";
 $("#alertQueue").innerHTML=ALERTS.map(a=>{
   const status=working.has(a.id)?"WORKING SET":held.has(a.id)?"HOLD":opened.has(a.id)?"REVIEWED":"NEW";
   return '<article class="alert-row '+(working.has(a.id)?"correlated ":"")+(held.has(a.id)?"held ":"")+'sev-'+a.sev.toLowerCase()+'"><div class="alert-time">'+esc(a.time)+'</div><div class="alert-sev">'+esc(a.sev)+'</div><div class="alert-source">'+esc(a.source)+'</div><div class="alert-main"><b>'+esc(a.title)+'</b><span>'+esc(a.client)+'</span><p>'+esc(a.summary)+'</p></div><div class="alert-status">'+status+'</div><button data-alert="'+esc(a.id)+'">INSPECT</button></article>'
 }).join("");
 $("#caseCards").innerHTML=s.incidentCreated?incidentCard(CASES["U1-003"]):'<div class="empty-incident"><b>NO ACTIVE INCIDENT</b><span>Inspect incoming alerts and build a working set. When the evidence supports correlation, create an incident.</span></div>';
 $("#historyCards").innerHTML=["U1-002","U1-001"].map(id=>{
   const c=CASES[id],closed=id==="U1-002"?"CLOSED / PRIOR OP":"TRAINING ARCHIVE";
   return '<article><div><small>'+esc(closed)+'</small><b>'+esc(c.id)+' // '+esc(c.title)+'</b><span>'+esc(c.topic)+'</span></div><button data-case="'+esc(c.id)+'">REVIEW CASE</button></article>'
 }).join("");
}
function incidentCard(c){return '<article class="queue-card assigned incident-card"><div class="queue-card-top"><small>'+esc(c.id)+' // ACTIVE INCIDENT</small><span class="priority-mini">'+esc(c.priority)+'</span></div><h2>'+esc(c.title)+'</h2><p>Northstar Health Services // '+esc(c.topic)+'</p><div class="queue-meta"><span>CORRELATED ALERTS</span><span>'+esc(c.records.length)+' INCIDENT RECORDS</span><span>'+esc(c.credits)+' EVIDENCE CREDITS</span></div><button data-case="'+esc(c.id)+'" class="primary">OPEN INCIDENT</button></article>'}
function openAlert(id){
 const a=ALERTS.find(x=>x.id===id);if(!a)return;
 const s=alertState();if(!s.opened.includes(id))s.opened.push(id);saveAlertState(s);renderWorkspace();
 const disposition=(s.working||[]).includes(id)?"WORKING SET":(s.held||[]).includes(id)?"HOLD":"UNTRIAGED";
 showModal('<div class="alert-modal-head"><small>'+esc(a.id)+' // '+esc(a.time)+' // '+esc(a.source)+'</small><span class="severity '+esc(a.sev.toLowerCase())+'">'+esc(a.sev)+'</span></div><h2>'+esc(a.title)+'</h2><p class="lead">'+esc(a.summary)+'</p><div class="alert-artifact"><small>OBSERVABLE DETAIL</small><p>'+esc(a.detail)+'</p></div><div class="triage-reminder"><b>TRIAGE QUESTION</b><span>Does this observation belong in the same working set as other Northstar activity? Correlation is a hypothesis until the evidence supports it.</span></div><div class="triage-actions"><button data-alert-action="working" data-alert-id="'+esc(a.id)+'">ADD TO WORKING SET</button><button data-alert-action="hold" data-alert-id="'+esc(a.id)+'">HOLD / NEED CONTEXT</button><button data-alert-action="clear" data-alert-id="'+esc(a.id)+'">CLEAR TRIAGE</button></div><p class="current-triage">CURRENT: <b>'+esc(disposition)+'</b></p>');
}
function triageAlert(id,action){
 const s=alertState();s.working=(s.working||[]).filter(x=>x!==id);s.held=(s.held||[]).filter(x=>x!==id);
 if(action==="working")s.working.push(id);if(action==="hold")s.held.push(id);
 saveAlertState(s);closeModal();renderWorkspace();
}
function createIncident(){
 const s=alertState();if((s.working||[]).length<2||s.incidentCreated)return;
 s.incidentCreated=true;saveAlertState(s);renderWorkspace();
 showModal('<h2>INCIDENT CREATED // U1-003</h2><p class="lead">Your working set has been escalated into an Ironcrest incident.</p><div class="incident-created"><b>CHAIN REACTION</b><span>NORTHSTAR HEALTH SERVICES</span><p>You have correlated '+s.working.length+' alerts. That correlation starts the investigation—it does not prove a complete attack path. Open the incident and test your hypothesis against telemetry and evidence.</p></div><button data-open-created="U1-003" class="primary-modal">OPEN INCIDENT →</button>');
}

function switchWorkspace(name){document.querySelectorAll(".workspace-tab").forEach(b=>b.classList.toggle("active",b.dataset.workspace===name));document.querySelectorAll(".workspace-panel").forEach(p=>p.classList.toggle("active",p.id==="workspace-"+name))}
function queue(){C=null;$("#console").classList.add("hidden");$("#briefing").classList.remove("hidden");$("#caseBrief").classList.add("hidden");$("#queueView").classList.remove("hidden");renderWorkspace()}
function openBrief(id){C=CASES[id];if(!C)return;loadState();$("#queueView").classList.add("hidden");$("#caseBrief").classList.remove("hidden");$("#briefId").textContent=C.id;$("#briefPriority").textContent="PRIORITY: "+C.priority;$("#briefTitle").textContent=C.title;$("#briefText").textContent=C.brief;$("#briefMission").textContent=C.mission;$("#briefResources").textContent=C.credits+" investigation credits. Additional evidence has a cost.";$("#briefStandard").textContent=C.standard;$("#roleSelect").innerHTML=C.roles.map(r=>'<option>'+esc(r)+'</option>').join("");$("#roleSelect").value=state.team||C.roles[0]}
$("#caseCards").onclick=e=>{const b=e.target.closest("[data-case]");if(b)openBrief(b.dataset.case)};
$("#historyCards").onclick=e=>{const b=e.target.closest("[data-case]");if(b)openBrief(b.dataset.case)};
$("#alertQueue").onclick=e=>{const b=e.target.closest("[data-alert]");if(b)openAlert(b.dataset.alert)};
$("#createIncident").onclick=createIncident;
$("#modalBody").addEventListener("click",e=>{
 const t=e.target.closest("[data-alert-action]");if(t){triageAlert(t.dataset.alertId,t.dataset.alertAction);return}
 const o=e.target.closest("[data-open-created]");if(o){closeModal();openBrief(o.dataset.openCreated)}
});

$("#openIncidentRecap").onclick=()=>showModal('<h2>INCIDENT RECAP // CAPTIVECRUNCH</h2><p class="lead">Microsoft Threat Intelligence reported a real campaign targeting travelers through hospitality and other captive-portal networks.</p><div class="intel-brief"><b>WHAT HAPPENED</b><p>Storm-2945 manipulated DNS and HTTP traffic from affected captive-portal networks so user traffic could be redirected through actor-controlled infrastructure. Microsoft observed phishing, credential and session-token theft, and malware delivery.</p><b>WHY DEFENDERS CARE</b><p>A network that appears routine or trusted can become part of the attack path. Defenders must correlate network behavior, user interaction, identity activity, and endpoint evidence rather than relying on the SSID or portal appearance alone.</p><b>ANALYST CAUTION</b><p>Use this incident as threat context—not as proof that a simulated Ironcrest case used the same actor or technique.</p></div>');
$("#openExamLens").onclick=()=>showModal('<h2>AP EXAM LENS // TOPIC 1.3</h2><p class="lead">Translate the real incident into the exact concepts College Board can ask you to identify or explain.</p><div class="exam-lens-grid"><div><b>EVIL TWIN</b><span>An adversary-operated wireless access point uses an SSID similar or identical to a legitimate network. Look for evidence of the impersonating access point—not merely “public Wi-Fi.”</span></div><div><b>JAMMING</b><span>Strong electromagnetic interference in the same frequency range prevents legitimate wireless communication. Think availability.</span></div><div><b>WAR DRIVING</b><span>Wireless reconnaissance used to detect beacons and gather network information while moving through an area.</span></div><div><b>ADVERSARY SKILL</b><span>Classify low- versus high-skilled adversaries from capability, tooling, and vulnerability use—not simply from the severity of impact.</span></div><div><b>PUBLIC-NETWORK PROTECTION</b><span>Verify the exact SSID and consider data sensitivity before joining an unencrypted network.</span></div><div><b>VPN</b><span>A VPN encrypts traffic to the VPN operator. It does not stop radio-frequency jamming and does not make every untrusted interaction safe.</span></div></div><p><b>EXAM HABIT:</b> OBSERVE → IDENTIFY THE MECHANISM → CITE THE EVIDENCE → SELECT THE APPROPRIATE CONTROL.</p>');


const intelContent={
 human:'<h2>IC-001 // Credential Harvesting Patterns</h2><p class="lead">Intelligence is context, not proof that a specific case matches a campaign.</p><div class="intel-brief"><b>OBSERVED PATTERNS</b><ul><li>Messages may combine authority or impersonation with urgency or threatened negative consequences.</li><li>Credential-harvesting pages imitate trusted services and request authentication information.</li><li>Credential exposure establishes that credentials were revealed; it does not by itself prove later account access.</li></ul><b>ANALYST QUESTIONS</b><ul><li>What exact language attempts to influence the target?</li><li>Did the user actually enter credentials?</li><li>What identity evidence exists after the exposure?</li></ul></div>',
 identity:'<h2>IC-002 // Suspicious Authentication Activity</h2><p class="lead">Correlate authentication events before deciding an account was compromised.</p><div class="intel-brief"><b>HIGH-VALUE OBSERVATIONS</b><ul><li>Many failed attempts in a short period.</li><li>Unusual sign-in time or unfamiliar device/source.</li><li>A success following failures.</li><li>MFA changes, new sessions, mailbox rules, or other post-login activity.</li></ul><b>CAUTION</b><p>A failed login is not successful access. An unfamiliar device is suspicious context, not automatic proof of malicious activity.</p></div>',
 wireless:'<h2>IC-003 // Public Network Threats</h2><p class="lead">Identify the mechanism from observable evidence.</p><div class="intel-brief"><b>EVIL TWIN</b><p>An adversary-operated access point imitates a legitimate SSID so users connect through it.</p><b>JAMMING</b><p>Radio-frequency interference prevents legitimate wireless communication and affects availability.</p><b>WAR DRIVING</b><p>Wireless reconnaissance gathers information about networks while moving through an area.</p><b>PROTECTION</b><p>Verify the exact SSID, consider data sensitivity before joining open Wi-Fi, and understand that a VPN protects traffic confidentiality but does not stop RF jamming.</p></div>'
};
document.querySelectorAll("[data-intel]").forEach(b=>b.onclick=()=>showModal(intelContent[b.dataset.intel]||"<p>No briefing available.</p>"));
const drillContent={
 psn:'<h2>DRILL 01 // Proves or Supports?</h2><p class="lead">An identity log shows 12 failed attempts from an unfamiliar source followed by one successful login. The user has not yet been interviewed.</p><p><b>Claim:</b> “The attacker stole the user’s password and used it to access the account.”</p><button class="drill-choice" data-answer="psn-proves">PROVES</button><button class="drill-choice" data-answer="psn-supports">SUPPORTS</button><button class="drill-choice" data-answer="psn-need">NEED MORE EVIDENCE</button><div id="drillFeedback" class="drill-feedback"></div>',
 auth:'<h2>DRILL 02 // Authentication Triage</h2><p class="lead">02:13 — four failed password attempts from an unknown browser. 02:14 — successful login from that browser. 02:17 — MFA settings changed.</p><p><b>Which observation most strongly strengthens the hypothesis of unauthorized post-login activity?</b></p><button class="drill-choice" data-answer="auth-fails">The failed attempts</button><button class="drill-choice" data-answer="auth-success">The successful login</button><button class="drill-choice" data-answer="auth-mfa">The MFA settings change</button><div id="drillFeedback" class="drill-feedback"></div>',
 wireless:'<h2>DRILL 03 // Name the Mechanism</h2><p class="lead">A venue advertises “HarborCenter-Guest.” A second access point named “HarborCenter_Guest” appears nearby and presents a sign-in portal.</p><p><b>Which mechanism is most directly supported?</b></p><button class="drill-choice" data-answer="wireless-evil">Evil twin</button><button class="drill-choice" data-answer="wireless-jam">Jamming</button><button class="drill-choice" data-answer="wireless-war">War driving</button><div id="drillFeedback" class="drill-feedback"></div>'
};
document.querySelectorAll("[data-drill]").forEach(b=>b.onclick=()=>showModal(drillContent[b.dataset.drill]));


document.querySelectorAll("[data-tool]").forEach(b=>b.onclick=()=>{
 const tool=b.dataset.tool;
 if(tool==="psn")showModal('<h2>Proves / Supports / Need</h2><p class="lead">Use this before making an incident claim.</p><div class="tool-modal-grid"><div><b>PROVES</b>What can you state directly as fact from the evidence?</div><div><b>SUPPORTS</b>What conclusion does the evidence suggest but not independently prove?</div><div><b>NEED</b>What additional evidence would strengthen, challenge, or resolve the conclusion?</div></div><p><b>Analyst rule:</b> If your sentence goes beyond the observable evidence, move it from PROVES to SUPPORTS—or identify what you NEED.</p>');
 if(tool==="auth")showModal('<h2>Authentication Analyzer</h2><p class="lead">Triage suspicious identity activity with the same routine every time.</p><ol class="tool-checklist"><li>Look for many failed attempts in a short period.</li><li>Compare login time with the user\'s normal pattern.</li><li>Identify unfamiliar devices, source addresses, or locations.</li><li>Look for a success after failures.</li><li>Correlate MFA changes, new sessions, mailbox rules, or other post-login activity.</li><li>Separate credential exposure from evidence of actual account access.</li></ol><p><b>Finish with:</b> What does this PROVE, SUPPORT, and what do you still NEED?</p>');
 if(tool==="ioc")showModal('<h2>IOC Workbench</h2><p class="lead">Classify the observable before assigning meaning.</p><div class="tool-modal-grid"><div><b>IDENTIFIER</b>IP address, domain, URL, hash, username, hostname, email address.</div><div><b>CONTEXT</b>Where was it observed? When? In which data source? What action occurred?</div><div><b>ASSESSMENT</b>Benign, suspicious, malicious, or unknown must be supported by evidence.</div></div><p><b>Analyst rule:</b> An unfamiliar artifact is not automatically malicious. Record the context that makes it relevant.</p>');
});
$("#consoleToolkit").onclick=()=>showModal('<h2>Analyst Toolkit</h2><p class="lead">Use these routines while the case is open. They guide reasoning; they do not grade the case.</p><div class="tool-modal-grid"><div><b>PROVES</b>Directly established by the evidence.</div><div><b>SUPPORTS</b>Suggested by correlation or context, but not independently proven.</div><div><b>NEED</b>Evidence that would strengthen, challenge, or resolve the conclusion.</div></div><h3>Authentication triage</h3><ol class="tool-checklist"><li>Failed-attempt pattern</li><li>Unusual time</li><li>Unknown device / source</li><li>Success after failures</li><li>Post-login changes or activity</li></ol><h3>Observable / IOC routine</h3><p>Classify the artifact first → record where and when it appeared → decide whether the context makes it benign, suspicious, malicious, or still unknown.</p>');
$("#backQueue").onclick=queue;$("#caseQueue").onclick=queue;
$("#acceptCase").onclick=()=>{state.team=$("#roleSelect").value;save();$("#briefing").classList.add("hidden");$("#console").classList.remove("hidden");configure();render()};
function configure(){$("#activeCaseId").textContent=C.id;$("#activeCaseTitle").textContent=C.title;$("#activePriority").textContent=C.priority;$("#telemetryNav").textContent=C.telemetryName;$("#telemetryKicker").textContent=C.telemetryKicker;$("#telemetryTitle").textContent=C.telemetryName;$("#objectiveText").textContent=C.objective;$("#objectiveSteps").innerHTML=C.objectiveSteps.map(x=>"<li>"+esc(x)+"</li>").join("");$("#drawerLabel").textContent=C.recordLabel;$("#search").placeholder="Search "+C.telemetryName.toLowerCase()+"…";$("#telemetryHeaders").innerHTML=C.columns.map(x=>"<th>"+esc(x.label)+"</th>").join("");$("#eventFilter").innerHTML='<option value="">All observation types</option>'+[...new Set(C.records.map(x=>x.event))].sort().map(x=>"<option>"+esc(x)+"</option>").join("");$("#resultFilter").innerHTML='<option value="">All statuses</option>'+[...new Set(C.records.map(x=>x.result))].sort().map(x=>"<option>"+esc(x)+"</option>").join("");buildCustomAssessment()}
function buildCustomAssessment(){const a=C.assessment||{fields:[]};$("#customAssessment").innerHTML=(a.fields||[]).map(f=>{const req=f.required?" required":"";if(f.type==="select")return '<label>'+esc(f.label)+'<select id="af_'+esc(f.id)+'"'+req+'><option value="">Select…</option>'+f.options.map(o=>"<option>"+esc(o)+"</option>").join("")+"</select></label>";if(f.type==="textarea")return '<label>'+esc(f.label)+'<textarea id="af_'+esc(f.id)+'" placeholder="'+esc(f.placeholder||"")+'"'+req+'></textarea></label>';return '<label>'+esc(f.label)+'<input id="af_'+esc(f.id)+'" placeholder="'+esc(f.placeholder||"")+'"'+req+'></label>'}).join("")}
$("#closeDrawer").onclick=()=>$("#drawer").classList.add("hidden");$("#closeModal").onclick=closeModal;
$("#resetCase").onclick=()=>showModal("<h2>Reset Case "+esc(C.id)+"?</h2><p>This clears this browser's case file, evidence requests, notes, and assessment for <b>"+esc(C.id)+"</b>. Other cases are not affected.</p><button type=\"button\" id=\"confirmReset\" class=\"danger modal-action\">RESET CASE</button>");
document.querySelectorAll("#console aside nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#console aside nav button,.view").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.view).classList.add("active");if(b.dataset.view==="assessment")renderAssessment()});
function renderLogs(){const q=$("#search").value.toLowerCase(),ef=$("#eventFilter").value,rf=$("#resultFilter").value;const rows=C.records.filter(x=>(!q||Object.values(x).join(" ").toLowerCase().includes(q))&&(!ef||x.event===ef)&&(!rf||x.result===rf));$("#eventCount").textContent=rows.length+" records";$("#logRows").innerHTML=rows.map(x=>'<tr data-id="'+esc(x.id)+'">'+C.columns.map(col=>'<td class="'+(col.key==="result"?"result-"+String(x[col.key]).toLowerCase():"")+'">'+esc(x[col.key])+"</td>").join("")+"</tr>").join("")}
["search","eventFilter","resultFilter"].forEach(id=>$("#"+id).addEventListener(id==="search"?"input":"change",renderLogs));$("#clearFilters").onclick=()=>{$("#search").value="";$("#eventFilter").value="";$("#resultFilter").value="";renderLogs()};$("#logRows").onclick=e=>{const row=e.target.closest("tr[data-id]");if(row)openRecord(row.dataset.id)};
function openRecord(id){selected=C.records.find(x=>x.id===id);if(!selected)return;$("#drawerTitle").textContent=selected.id+" // "+selected.event;$("#drawerBody").innerHTML=Object.entries(selected).map(([k,v])=>'<div class="detailrow"><span>'+esc(k.toUpperCase())+'</span><span>'+esc(v)+"</span></div>").join("");$("#drawer").classList.remove("hidden")}
$("#pinEvent").onclick=()=>{if(!selected)return;showModal("<h2>Add "+esc(selected.id)+" to Case</h2><p><b>Why does this record matter?</b></p><p class=\"lead\">Explain what you noticed or how it relates to your current hypothesis.</p><textarea id=\"eventReason\" rows=\"4\" placeholder=\"Analyst observation…\" required></textarea><button type=\"button\" id=\"confirmPin\" class=\"primary modal-action\" disabled>ADD TO CASE FILE</button>")};
function renderEvidence(){const total=C.credits||3;$("#creditDots").textContent=Array(state.credits).fill("●").join(" ")+" "+Array(total-state.credits).fill("○").join(" ");$("#evidenceCards").innerHTML=C.evidence.map(ev=>{const u=state.unlocked.includes(ev.id);return '<article class="ecard '+(u?"unlocked":"")+'"><small>'+(u?"UNLOCKED":"AVAILABLE // 1 CREDIT")+"</small><h3>"+esc(ev.title)+"</h3><p>"+esc(ev.desc)+'</p><button data-e="'+esc(ev.id)+'">'+(u?"VIEW EVIDENCE":"REQUEST EVIDENCE")+"</button></article>"}).join("")}
$("#evidenceCards").onclick=e=>{const b=e.target.closest("[data-e]");if(b)requestEvidence(b.dataset.e)};
function requestEvidence(id){const ev=C.evidence.find(x=>x.id===id);if(!ev)return;pendingEvidence=ev;if(state.unlocked.includes(id))return showEvidence(ev);if(state.credits<=0)return showModal("<h2>No credits remaining</h2><p>Work with the evidence your team has already collected.</p>");showModal("<h2>Evidence Request: "+esc(ev.title)+"</h2><p>What investigative question are you trying to answer, and why would this source help?</p><textarea id=\"evidenceQuestion\" rows=\"4\" placeholder=\"Enter your investigative question…\" required></textarea><button type=\"button\" id=\"confirmSpend\" class=\"primary modal-action\" disabled>SPEND 1 CREDIT & REVEAL</button>")}
function showEvidence(ev){pendingEvidence=ev;const added=state.evidenceAdded.includes(ev.id);showModal(ev.content+'<div class="evidence-question"><small>YOUR INVESTIGATIVE QUESTION</small><p>'+esc(state.evidenceQuestions[ev.id]||"Previously unlocked evidence")+'</p></div><button id="addEvidence" class="primary modal-action" '+(added?"disabled":"")+">"+(added?"ADDED TO CASE":"ADD TO CASE")+"</button>")}
$("#timelineForm").onsubmit=e=>{e.preventDefault();const t=$("#timelineText").value.trim();if(!t)return;state.timeline.push({type:"note",time:$("#timelineTime").value||"—",title:"Analyst Observation",source:"Manual entry",observation:t});$("#timelineTime").value=$("#timelineText").value="";save();renderTimeline()};
function sortTimeline(items){return items.map((x,i)=>({...x,_i:i})).sort((a,b)=>{const ta=/^\d\d:\d\d/.test(a.time)?a.time:"99:99:99",tb=/^\d\d:\d\d/.test(b.time)?b.time:"99:99:99";return ta.localeCompare(tb)})}
function renderTimeline(){const items=sortTimeline(state.timeline);$("#timelineList").innerHTML=items.length?items.map(x=>'<div class="entry '+esc(x.type||"legacy")+'"><div class="entrytop"><span class="badge">'+esc(String(x.type||"legacy").toUpperCase())+"</span><b>"+esc(x.time||"—")+'</b><button type="button" data-del="'+x._i+'" title="Remove finding">×</button></div><h3>'+esc(x.title||"Finding")+'</h3><div class="entrysource">'+esc(x.source||"")+"</div><p><strong>Analyst observation:</strong> "+esc(x.observation||x.text||"")+"</p></div>").join(""):'<p class="hint">No findings in the case file yet.</p>';renderAssessment()}
$("#timelineList").onclick=e=>{const b=e.target.closest("[data-del]");if(!b)return;const i=Number(b.dataset.del);if(Number.isInteger(i)&&i>=0&&i<state.timeline.length){state.timeline.splice(i,1);save();renderTimeline()}};
$("#caseNotes").oninput=e=>{state.notes=e.target.value;save();$("#saveFlag").textContent="Saved.";renderAssessment()};
function customValues(){const vals={};(C.assessment.fields||[]).forEach(f=>{const el=$("#af_"+f.id);vals[f.id]=el?el.value.trim():""});return vals}
function populateAssessment(){const a=state.assessment||{};$("#disposition").value=a.disposition||"";$("#happened").value=a.happened||"";$("#proves").value=a.proves||"";$("#supports").value=a.supports||"";$("#need").value=a.need||"";$("#nextAction").value=a.nextAction||"";(C.assessment.fields||[]).forEach(f=>{const el=$("#af_"+f.id);if(el)el.value=(a.custom||{})[f.id]||""})}
function customReportHtml(a){const labels=C.assessment.reportLabels||{};return Object.entries(a.custom||{}).map(([k,v])=>'<div><small>'+esc(labels[k]||k.toUpperCase())+"</small><p>"+esc(v)+"</p></div>").join("")}
function reportText(){const a=state.assessment||{},labels=C.assessment.reportLabels||{};const custom=Object.entries(a.custom||{}).map(([k,v])=>"\n"+(labels[k]||k.toUpperCase())+"\n"+v).join("");const findings=sortTimeline(state.timeline).map(x=>"- "+(x.time||"—")+" | "+(x.title||"Finding")+": "+(x.observation||x.text||"")).join("\n");return "IRONCREST CYBER PARTNERS — SOC BRIEFING\nCase: "+C.id+" — "+C.title+"\nAnalyst Team: "+(state.team||"Unassigned")+"\n\nDISPOSITION\n"+(a.disposition||"")+custom+"\n\nINCIDENT ASSESSMENT\n"+(a.happened||"")+"\n\nPROVES\n"+(a.proves||"")+"\n\nSUPPORTS\n"+(a.supports||"")+"\n\nNEED\n"+(a.need||"")+"\n\nRECOMMENDED NEXT ACTION\n"+(a.nextAction||"")+"\n\nCASE FILE FINDINGS\n"+(findings||"No findings recorded.")}
function renderReport(){const a=state.assessment;if(!a)return;$("#reportDisposition").textContent=a.disposition;$("#reportBody").innerHTML='<div class="report-grid">'+customReportHtml(a)+'<div><small>ANALYST TEAM</small><p>'+esc(state.team)+'</p></div></div><section><small>INCIDENT ASSESSMENT</small><p>'+esc(a.happened)+'</p></section><div class="triple report-reasoning"><section><small>PROVES</small><p>'+esc(a.proves)+'</p></section><section><small>SUPPORTS</small><p>'+esc(a.supports)+'</p></section><section><small>NEED</small><p>'+esc(a.need)+'</p></section></div><section><small>RECOMMENDED NEXT ACTION</small><p>'+esc(a.nextAction)+'</p></section><section><small>CASE FILE FINDINGS</small>'+sortTimeline(state.timeline).map(x=>'<div class="report-finding"><b>'+esc(x.time)+" · "+esc(x.title)+"</b><span>"+esc(x.observation||x.text||"")+"</span></div>").join("")+"</section>"}
function renderAssessment(){if(!C||!state)return;$("#statusTimeline").textContent=state.timeline.length;$("#statusEvidence").textContent=state.unlocked.length+" / "+(C.credits||3);$("#statusNotes").textContent=state.notes.trim()?"SAVED":"NONE";$("#assessmentFindings").innerHTML=state.timeline.length?'<small>CASE FILE FINDINGS</small>'+sortTimeline(state.timeline).map(x=>'<div class="mini-finding"><b>'+esc(x.time)+" · "+esc(x.title)+"</b><span>"+esc(x.observation||x.text||"")+"</span></div>").join(""):'<p class="hint">Your case file has no findings yet. Return to the investigation before making a disposition.</p>';const done=!!state.assessment&&!editingAssessment;$("#assessmentForm").classList.toggle("hidden",done);$("#submitted").classList.toggle("hidden",!done);if(done)renderReport();else populateAssessment()}
$("#assessmentForm").onsubmit=e=>{e.preventDefault();state.assessment={disposition:$("#disposition").value,custom:customValues(),happened:$("#happened").value.trim(),proves:$("#proves").value.trim(),supports:$("#supports").value.trim(),need:$("#need").value.trim(),nextAction:$("#nextAction").value.trim()};editingAssessment=false;save();renderAssessment()};
$("#editAssessment").onclick=()=>{editingAssessment=true;renderAssessment();$("#assessmentForm").scrollIntoView({behavior:"smooth",block:"start"})};
$("#copyBriefing").onclick=async()=>{const t=reportText(),s=$("#copyStatus");try{await navigator.clipboard.writeText(t)}catch(e){const ta=document.createElement("textarea");ta.value=t;document.body.appendChild(ta);ta.select();document.execCommand("copy");ta.remove()}s.textContent="Copied — paste into Schoology.";setTimeout(()=>s.textContent="",3500)};
document.addEventListener("input",e=>{const id=e.target&&e.target.id;if(id==="eventReason"&&$("#confirmPin"))$("#confirmPin").disabled=!e.target.value.trim();if(id==="evidenceQuestion"&&$("#confirmSpend"))$("#confirmSpend").disabled=!e.target.value.trim();if(id==="evidenceReason"&&$("#confirmEvidence"))$("#confirmEvidence").disabled=!e.target.value.trim()},true);
document.addEventListener("click",e=>{const b=e.target.closest&&e.target.closest("button");if(!b)return;
if(b.classList.contains("drill-choice")){
 const f=$("#drillFeedback"),a=b.dataset.answer;
 const messages={
 "psn-proves":"Not yet. The log proves the failures and success occurred, but not how the credential was obtained or who used it.",
 "psn-supports":"The sequence supports suspicious or possibly unauthorized access, but the full claim goes beyond the evidence.",
 "psn-need":"Correct. You need additional evidence before claiming password theft and attacker use. Separate the observed login sequence from the cause.",
 "auth-fails":"Useful indicator, but failed attempts do not establish post-login activity.",
 "auth-success":"Stronger, but the question asks specifically for evidence of activity after access.",
 "auth-mfa":"Correct. The MFA change is post-login account activity and materially strengthens the unauthorized-access hypothesis.",
 "wireless-evil":"Correct. The near-match SSID plus sign-in portal directly supports an evil-twin / impersonating access-point hypothesis.",
 "wireless-jam":"Not from these observations. Jamming requires evidence of RF interference or availability disruption.",
 "wireless-war":"Not from these observations. War driving is reconnaissance; a nearby rogue SSID does not prove how it was discovered or deployed."
 };f.textContent=messages[a]||"";f.classList.add("show");return;
}
if(b.id==="confirmPin"){const t=$("#eventReason");if(!t||!t.value.trim()||!selected)return;state.timeline.push({type:"log",time:selected.time,title:selected.id+" — "+selected.event,source:C.columns.slice(1,3).map(x=>selected[x.key]).join(" · ")+" · "+selected.resource,observation:t.value.trim()});save();renderTimeline();closeModal();$("#drawer").classList.add("hidden")}else if(b.id==="confirmSpend"){const t=$("#evidenceQuestion");if(!t||!t.value.trim()||!pendingEvidence||state.credits<=0)return;if(!state.unlocked.includes(pendingEvidence.id)){state.credits--;state.unlocked.push(pendingEvidence.id)}state.evidenceQuestions[pendingEvidence.id]=t.value.trim();save();renderEvidence();showEvidence(pendingEvidence)}else if(b.id==="addEvidence"){if(b.disabled||!pendingEvidence)return;showModal(pendingEvidence.content+'<h3>Why does this evidence matter?</h3><p class="lead">Explain what it proves or supports in your investigation.</p><textarea id="evidenceReason" rows="4" placeholder="Analyst interpretation…"></textarea><button type="button" id="confirmEvidence" class="primary modal-action" disabled>ADD TO CASE FILE</button>')}else if(b.id==="confirmEvidence"){const t=$("#evidenceReason");if(!t||!t.value.trim()||!pendingEvidence)return;if(!state.evidenceAdded.includes(pendingEvidence.id)){state.evidenceAdded.push(pendingEvidence.id);state.timeline.push({type:"evidence",time:"EVIDENCE",title:pendingEvidence.title,source:"Evidence Locker",observation:t.value.trim()})}save();renderEvidence();renderTimeline();closeModal()}else if(b.id==="confirmReset"){const resetId=C.id;localStorage.removeItem(KEY);closeModal();openBrief(resetId)}},true);
function render(){$("#teamName").textContent=state.team;$("#caseNotes").value=state.notes;renderLogs();renderEvidence();renderTimeline();renderAssessment()}
queue()})();